// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: private/crm/v1/dto.proto

package crmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/neurochar/workflows/pkg/proto_pb/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatchCandidatesResumeRequestPayload struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Status        *types.CandidateResumeStatus                     `protobuf:"varint,1,opt,name=status,proto3,enum=types.v1.CandidateResumeStatus,oneof" json:"status,omitempty"`
	ErrorText     *PatchCandidatesResumeRequestPayload_ErrorText   `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3,oneof" json:"error_text,omitempty"`
	AnalyzeData   *PatchCandidatesResumeRequestPayload_AnalyzeData `protobuf:"bytes,3,opt,name=analyze_data,json=analyzeData,proto3,oneof" json:"analyze_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidatesResumeRequestPayload) Reset() {
	*x = PatchCandidatesResumeRequestPayload{}
	mi := &file_private_crm_v1_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidatesResumeRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidatesResumeRequestPayload) ProtoMessage() {}

func (x *PatchCandidatesResumeRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_private_crm_v1_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidatesResumeRequestPayload.ProtoReflect.Descriptor instead.
func (*PatchCandidatesResumeRequestPayload) Descriptor() ([]byte, []int) {
	return file_private_crm_v1_dto_proto_rawDescGZIP(), []int{0}
}

func (x *PatchCandidatesResumeRequestPayload) GetStatus() types.CandidateResumeStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return types.CandidateResumeStatus(0)
}

func (x *PatchCandidatesResumeRequestPayload) GetErrorText() *PatchCandidatesResumeRequestPayload_ErrorText {
	if x != nil {
		return x.ErrorText
	}
	return nil
}

func (x *PatchCandidatesResumeRequestPayload) GetAnalyzeData() *PatchCandidatesResumeRequestPayload_AnalyzeData {
	if x != nil {
		return x.AnalyzeData
	}
	return nil
}

type PatchCandidatesResumeRequest struct {
	state            protoimpl.MessageState               `protogen:"open.v1"`
	Id               string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload          *PatchCandidatesResumeRequestPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Version          int64                                `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	SkipVersionCheck bool                                 `protobuf:"varint,4,opt,name=skip_version_check,json=skipVersionCheck,proto3" json:"skip_version_check,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PatchCandidatesResumeRequest) Reset() {
	*x = PatchCandidatesResumeRequest{}
	mi := &file_private_crm_v1_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidatesResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidatesResumeRequest) ProtoMessage() {}

func (x *PatchCandidatesResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_crm_v1_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidatesResumeRequest.ProtoReflect.Descriptor instead.
func (*PatchCandidatesResumeRequest) Descriptor() ([]byte, []int) {
	return file_private_crm_v1_dto_proto_rawDescGZIP(), []int{1}
}

func (x *PatchCandidatesResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchCandidatesResumeRequest) GetPayload() *PatchCandidatesResumeRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PatchCandidatesResumeRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PatchCandidatesResumeRequest) GetSkipVersionCheck() bool {
	if x != nil {
		return x.SkipVersionCheck
	}
	return false
}

type PatchCandidatesResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidatesResumeResponse) Reset() {
	*x = PatchCandidatesResumeResponse{}
	mi := &file_private_crm_v1_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidatesResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidatesResumeResponse) ProtoMessage() {}

func (x *PatchCandidatesResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_crm_v1_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidatesResumeResponse.ProtoReflect.Descriptor instead.
func (*PatchCandidatesResumeResponse) Descriptor() ([]byte, []int) {
	return file_private_crm_v1_dto_proto_rawDescGZIP(), []int{2}
}

type PatchCandidatesResumeRequestPayload_ErrorText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text,proto3,oneof" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidatesResumeRequestPayload_ErrorText) Reset() {
	*x = PatchCandidatesResumeRequestPayload_ErrorText{}
	mi := &file_private_crm_v1_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidatesResumeRequestPayload_ErrorText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidatesResumeRequestPayload_ErrorText) ProtoMessage() {}

func (x *PatchCandidatesResumeRequestPayload_ErrorText) ProtoReflect() protoreflect.Message {
	mi := &file_private_crm_v1_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidatesResumeRequestPayload_ErrorText.ProtoReflect.Descriptor instead.
func (*PatchCandidatesResumeRequestPayload_ErrorText) Descriptor() ([]byte, []int) {
	return file_private_crm_v1_dto_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PatchCandidatesResumeRequestPayload_ErrorText) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type PatchCandidatesResumeRequestPayload_AnalyzeData struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Data          *types.CandidateResumeAnalyzeData `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidatesResumeRequestPayload_AnalyzeData) Reset() {
	*x = PatchCandidatesResumeRequestPayload_AnalyzeData{}
	mi := &file_private_crm_v1_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidatesResumeRequestPayload_AnalyzeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidatesResumeRequestPayload_AnalyzeData) ProtoMessage() {}

func (x *PatchCandidatesResumeRequestPayload_AnalyzeData) ProtoReflect() protoreflect.Message {
	mi := &file_private_crm_v1_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidatesResumeRequestPayload_AnalyzeData.ProtoReflect.Descriptor instead.
func (*PatchCandidatesResumeRequestPayload_AnalyzeData) Descriptor() ([]byte, []int) {
	return file_private_crm_v1_dto_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PatchCandidatesResumeRequestPayload_AnalyzeData) GetData() *types.CandidateResumeAnalyzeData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_private_crm_v1_dto_proto protoreflect.FileDescriptor

const file_private_crm_v1_dto_proto_rawDesc = "" +
	"\n" +
	"\x18private/crm/v1/dto.proto\x12\x06crm.v1\x1a\x1ccommon/types/crm_types.proto\x1a\x1bbuf/validate/validate.proto\"\xd0\x03\n" +
	"#PatchCandidatesResumeRequestPayload\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.types.v1.CandidateResumeStatusH\x00R\x06status\x88\x01\x01\x12Y\n" +
	"\n" +
	"error_text\x18\x02 \x01(\v25.crm.v1.PatchCandidatesResumeRequestPayload.ErrorTextH\x01R\terrorText\x88\x01\x01\x12_\n" +
	"\fanalyze_data\x18\x03 \x01(\v27.crm.v1.PatchCandidatesResumeRequestPayload.AnalyzeDataH\x02R\vanalyzeData\x88\x01\x01\x1a-\n" +
	"\tErrorText\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x88\x01\x01B\a\n" +
	"\x05_text\x1aU\n" +
	"\vAnalyzeData\x12=\n" +
	"\x04data\x18\x01 \x01(\v2$.types.v1.CandidateResumeAnalyzeDataH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_dataB\t\n" +
	"\a_statusB\r\n" +
	"\v_error_textB\x0f\n" +
	"\r_analyze_data\"\xcf\x01\n" +
	"\x1cPatchCandidatesResumeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12M\n" +
	"\apayload\x18\x02 \x01(\v2+.crm.v1.PatchCandidatesResumeRequestPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12,\n" +
	"\x12skip_version_check\x18\x04 \x01(\bR\x10skipVersionCheck\"\x1f\n" +
	"\x1dPatchCandidatesResumeResponseB\x91\x01\n" +
	"\n" +
	"com.crm.v1B\bDtoProtoP\x01Z@github.com/neurochar/workflows/pkg/proto_pb/private/crm/v1;crmv1\xa2\x02\x03CXX\xaa\x02\x06Crm.V1\xca\x02\x06Crm\\V1\xe2\x02\x12Crm\\V1\\GPBMetadata\xea\x02\aCrm::V1b\x06proto3"

var (
	file_private_crm_v1_dto_proto_rawDescOnce sync.Once
	file_private_crm_v1_dto_proto_rawDescData []byte
)

func file_private_crm_v1_dto_proto_rawDescGZIP() []byte {
	file_private_crm_v1_dto_proto_rawDescOnce.Do(func() {
		file_private_crm_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_crm_v1_dto_proto_rawDesc), len(file_private_crm_v1_dto_proto_rawDesc)))
	})
	return file_private_crm_v1_dto_proto_rawDescData
}

var file_private_crm_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_private_crm_v1_dto_proto_goTypes = []any{
	(*PatchCandidatesResumeRequestPayload)(nil),             // 0: crm.v1.PatchCandidatesResumeRequestPayload
	(*PatchCandidatesResumeRequest)(nil),                    // 1: crm.v1.PatchCandidatesResumeRequest
	(*PatchCandidatesResumeResponse)(nil),                   // 2: crm.v1.PatchCandidatesResumeResponse
	(*PatchCandidatesResumeRequestPayload_ErrorText)(nil),   // 3: crm.v1.PatchCandidatesResumeRequestPayload.ErrorText
	(*PatchCandidatesResumeRequestPayload_AnalyzeData)(nil), // 4: crm.v1.PatchCandidatesResumeRequestPayload.AnalyzeData
	(types.CandidateResumeStatus)(0),                        // 5: types.v1.CandidateResumeStatus
	(*types.CandidateResumeAnalyzeData)(nil),                // 6: types.v1.CandidateResumeAnalyzeData
}
var file_private_crm_v1_dto_proto_depIdxs = []int32{
	5, // 0: crm.v1.PatchCandidatesResumeRequestPayload.status:type_name -> types.v1.CandidateResumeStatus
	3, // 1: crm.v1.PatchCandidatesResumeRequestPayload.error_text:type_name -> crm.v1.PatchCandidatesResumeRequestPayload.ErrorText
	4, // 2: crm.v1.PatchCandidatesResumeRequestPayload.analyze_data:type_name -> crm.v1.PatchCandidatesResumeRequestPayload.AnalyzeData
	0, // 3: crm.v1.PatchCandidatesResumeRequest.payload:type_name -> crm.v1.PatchCandidatesResumeRequestPayload
	6, // 4: crm.v1.PatchCandidatesResumeRequestPayload.AnalyzeData.data:type_name -> types.v1.CandidateResumeAnalyzeData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_private_crm_v1_dto_proto_init() }
func file_private_crm_v1_dto_proto_init() {
	if File_private_crm_v1_dto_proto != nil {
		return
	}
	file_private_crm_v1_dto_proto_msgTypes[0].OneofWrappers = []any{}
	file_private_crm_v1_dto_proto_msgTypes[3].OneofWrappers = []any{}
	file_private_crm_v1_dto_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_crm_v1_dto_proto_rawDesc), len(file_private_crm_v1_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_crm_v1_dto_proto_goTypes,
		DependencyIndexes: file_private_crm_v1_dto_proto_depIdxs,
		MessageInfos:      file_private_crm_v1_dto_proto_msgTypes,
	}.Build()
	File_private_crm_v1_dto_proto = out.File
	file_private_crm_v1_dto_proto_goTypes = nil
	file_private_crm_v1_dto_proto_depIdxs = nil
}
