// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: private/crm/v1/service.proto

package crmv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_private_crm_v1_service_proto protoreflect.FileDescriptor

const file_private_crm_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1cprivate/crm/v1/service.proto\x12\x06crm.v1\x1a\x18private/crm/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2{\n" +
	"\x11CrmPrivateService\x12f\n" +
	"\x15PatchCandidatesResume\x12$.crm.v1.PatchCandidatesResumeRequest\x1a%.crm.v1.PatchCandidatesResumeResponse\"\x00B\x95\x01\n" +
	"\n" +
	"com.crm.v1B\fServiceProtoP\x01Z@github.com/neurochar/workflows/pkg/proto_pb/private/crm/v1;crmv1\xa2\x02\x03CXX\xaa\x02\x06Crm.V1\xca\x02\x06Crm\\V1\xe2\x02\x12Crm\\V1\\GPBMetadata\xea\x02\aCrm::V1b\x06proto3"

var file_private_crm_v1_service_proto_goTypes = []any{
	(*PatchCandidatesResumeRequest)(nil),  // 0: crm.v1.PatchCandidatesResumeRequest
	(*PatchCandidatesResumeResponse)(nil), // 1: crm.v1.PatchCandidatesResumeResponse
}
var file_private_crm_v1_service_proto_depIdxs = []int32{
	0, // 0: crm.v1.CrmPrivateService.PatchCandidatesResume:input_type -> crm.v1.PatchCandidatesResumeRequest
	1, // 1: crm.v1.CrmPrivateService.PatchCandidatesResume:output_type -> crm.v1.PatchCandidatesResumeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_private_crm_v1_service_proto_init() }
func file_private_crm_v1_service_proto_init() {
	if File_private_crm_v1_service_proto != nil {
		return
	}
	file_private_crm_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_crm_v1_service_proto_rawDesc), len(file_private_crm_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_crm_v1_service_proto_goTypes,
		DependencyIndexes: file_private_crm_v1_service_proto_depIdxs,
	}.Build()
	File_private_crm_v1_service_proto = out.File
	file_private_crm_v1_service_proto_goTypes = nil
	file_private_crm_v1_service_proto_depIdxs = nil
}
