// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: private/crm/v1/service.proto

package crmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrmPrivateService_PatchCandidatesResume_FullMethodName = "/crm.v1.CrmPrivateService/PatchCandidatesResume"
)

// CrmPrivateServiceClient is the client API for CrmPrivateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrmPrivateServiceClient interface {
	// Обновить резюме кандидата
	PatchCandidatesResume(ctx context.Context, in *PatchCandidatesResumeRequest, opts ...grpc.CallOption) (*PatchCandidatesResumeResponse, error)
}

type crmPrivateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrmPrivateServiceClient(cc grpc.ClientConnInterface) CrmPrivateServiceClient {
	return &crmPrivateServiceClient{cc}
}

func (c *crmPrivateServiceClient) PatchCandidatesResume(ctx context.Context, in *PatchCandidatesResumeRequest, opts ...grpc.CallOption) (*PatchCandidatesResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchCandidatesResumeResponse)
	err := c.cc.Invoke(ctx, CrmPrivateService_PatchCandidatesResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrmPrivateServiceServer is the server API for CrmPrivateService service.
// All implementations must embed UnimplementedCrmPrivateServiceServer
// for forward compatibility.
type CrmPrivateServiceServer interface {
	// Обновить резюме кандидата
	PatchCandidatesResume(context.Context, *PatchCandidatesResumeRequest) (*PatchCandidatesResumeResponse, error)
	mustEmbedUnimplementedCrmPrivateServiceServer()
}

// UnimplementedCrmPrivateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrmPrivateServiceServer struct{}

func (UnimplementedCrmPrivateServiceServer) PatchCandidatesResume(context.Context, *PatchCandidatesResumeRequest) (*PatchCandidatesResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchCandidatesResume not implemented")
}
func (UnimplementedCrmPrivateServiceServer) mustEmbedUnimplementedCrmPrivateServiceServer() {}
func (UnimplementedCrmPrivateServiceServer) testEmbeddedByValue()                           {}

// UnsafeCrmPrivateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrmPrivateServiceServer will
// result in compilation errors.
type UnsafeCrmPrivateServiceServer interface {
	mustEmbedUnimplementedCrmPrivateServiceServer()
}

func RegisterCrmPrivateServiceServer(s grpc.ServiceRegistrar, srv CrmPrivateServiceServer) {
	// If the following call panics, it indicates UnimplementedCrmPrivateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrmPrivateService_ServiceDesc, srv)
}

func _CrmPrivateService_PatchCandidatesResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCandidatesResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPrivateServiceServer).PatchCandidatesResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPrivateService_PatchCandidatesResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPrivateServiceServer).PatchCandidatesResume(ctx, req.(*PatchCandidatesResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrmPrivateService_ServiceDesc is the grpc.ServiceDesc for CrmPrivateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrmPrivateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crm.v1.CrmPrivateService",
	HandlerType: (*CrmPrivateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatchCandidatesResume",
			Handler:    _CrmPrivateService_PatchCandidatesResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private/crm/v1/service.proto",
}
