// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/types/tenant_types.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TextId        string                 `protobuf:"bytes,3,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_common_types_tenant_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_tenant_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_common_types_tenant_types_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Tenant) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_common_types_tenant_types_proto protoreflect.FileDescriptor

const file_common_types_tenant_types_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon/types/tenant_types.proto\x12\btypes.v1\"_\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x17\n" +
	"\atext_id\x18\x03 \x01(\tR\x06textId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04nameB\xa3\x01\n" +
	"\fcom.types.v1B\x10TenantTypesProtoP\x01Z@github.com/neurochar/workflows/pkg/proto_pb/common/types;typesv1\xa2\x02\x03TXX\xaa\x02\bTypes.V1\xca\x02\bTypes\\V1\xe2\x02\x14Types\\V1\\GPBMetadata\xea\x02\tTypes::V1b\x06proto3"

var (
	file_common_types_tenant_types_proto_rawDescOnce sync.Once
	file_common_types_tenant_types_proto_rawDescData []byte
)

func file_common_types_tenant_types_proto_rawDescGZIP() []byte {
	file_common_types_tenant_types_proto_rawDescOnce.Do(func() {
		file_common_types_tenant_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_tenant_types_proto_rawDesc), len(file_common_types_tenant_types_proto_rawDesc)))
	})
	return file_common_types_tenant_types_proto_rawDescData
}

var file_common_types_tenant_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_types_tenant_types_proto_goTypes = []any{
	(*Tenant)(nil), // 0: types.v1.Tenant
}
var file_common_types_tenant_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_types_tenant_types_proto_init() }
func file_common_types_tenant_types_proto_init() {
	if File_common_types_tenant_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_tenant_types_proto_rawDesc), len(file_common_types_tenant_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_tenant_types_proto_goTypes,
		DependencyIndexes: file_common_types_tenant_types_proto_depIdxs,
		MessageInfos:      file_common_types_tenant_types_proto_msgTypes,
	}.Build()
	File_common_types_tenant_types_proto = out.File
	file_common_types_tenant_types_proto_goTypes = nil
	file_common_types_tenant_types_proto_depIdxs = nil
}
