// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/types/types.proto

package typesv1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_types_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_types_types_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{0}
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Filename      *string                `protobuf:"bytes,3,opt,name=filename,proto3,oneof" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_common_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *File) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

type FilesMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           map[string]*File       `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesMap) Reset() {
	*x = FilesMap{}
	mi := &file_common_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesMap) ProtoMessage() {}

func (x *FilesMap) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesMap.ProtoReflect.Descriptor instead.
func (*FilesMap) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *FilesMap) GetMap() map[string]*File {
	if x != nil {
		return x.Map
	}
	return nil
}

type OptionalDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *date.Date             `protobuf:"bytes,1,opt,name=date,proto3,oneof" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalDate) Reset() {
	*x = OptionalDate{}
	mi := &file_common_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalDate) ProtoMessage() {}

func (x *OptionalDate) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalDate.ProtoReflect.Descriptor instead.
func (*OptionalDate) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalDate) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

var File_common_types_types_proto protoreflect.FileDescriptor

const file_common_types_types_proto_rawDesc = "" +
	"\n" +
	"\x18common/types/types.proto\x12\btypes.v1\x1a\x16google/type/date.proto\"b\n" +
	"\x04File\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bfilename\x18\x03 \x01(\tH\x01R\bfilename\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_filename\"\x81\x01\n" +
	"\bFilesMap\x12-\n" +
	"\x03map\x18\x01 \x03(\v2\x1b.types.v1.FilesMap.MapEntryR\x03map\x1aF\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.types.v1.FileR\x05value:\x028\x01\"C\n" +
	"\fOptionalDate\x12*\n" +
	"\x04date\x18\x01 \x01(\v2\x11.google.type.DateH\x00R\x04date\x88\x01\x01B\a\n" +
	"\x05_date*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02B\x9d\x01\n" +
	"\fcom.types.v1B\n" +
	"TypesProtoP\x01Z@github.com/neurochar/workflows/pkg/proto_pb/common/types;typesv1\xa2\x02\x03TXX\xaa\x02\bTypes.V1\xca\x02\bTypes\\V1\xe2\x02\x14Types\\V1\\GPBMetadata\xea\x02\tTypes::V1b\x06proto3"

var (
	file_common_types_types_proto_rawDescOnce sync.Once
	file_common_types_types_proto_rawDescData []byte
)

func file_common_types_types_proto_rawDescGZIP() []byte {
	file_common_types_types_proto_rawDescOnce.Do(func() {
		file_common_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_types_proto_rawDesc), len(file_common_types_types_proto_rawDesc)))
	})
	return file_common_types_types_proto_rawDescData
}

var file_common_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_types_types_proto_goTypes = []any{
	(Gender)(0),          // 0: types.v1.Gender
	(*File)(nil),         // 1: types.v1.File
	(*FilesMap)(nil),     // 2: types.v1.FilesMap
	(*OptionalDate)(nil), // 3: types.v1.OptionalDate
	nil,                  // 4: types.v1.FilesMap.MapEntry
	(*date.Date)(nil),    // 5: google.type.Date
}
var file_common_types_types_proto_depIdxs = []int32{
	4, // 0: types.v1.FilesMap.map:type_name -> types.v1.FilesMap.MapEntry
	5, // 1: types.v1.OptionalDate.date:type_name -> google.type.Date
	1, // 2: types.v1.FilesMap.MapEntry.value:type_name -> types.v1.File
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_types_types_proto_init() }
func file_common_types_types_proto_init() {
	if File_common_types_types_proto != nil {
		return
	}
	file_common_types_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_types_types_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_types_proto_rawDesc), len(file_common_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_types_proto_goTypes,
		DependencyIndexes: file_common_types_types_proto_depIdxs,
		EnumInfos:         file_common_types_types_proto_enumTypes,
		MessageInfos:      file_common_types_types_proto_msgTypes,
	}.Build()
	File_common_types_types_proto = out.File
	file_common_types_types_proto_goTypes = nil
	file_common_types_types_proto_depIdxs = nil
}
