// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/types/users_tenant_types.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountTenant struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Id              string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64                     `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId        string                    `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleId          uint64                    `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Email           string                    `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	IsConfirmed     bool                      `protobuf:"varint,6,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"`
	IsEmailVerified bool                      `protobuf:"varint,7,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	IsBlocked       bool                      `protobuf:"varint,8,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	ProfileName     string                    `protobuf:"bytes,9,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	ProfileSurname  string                    `protobuf:"bytes,10,opt,name=profile_surname,json=profileSurname,proto3" json:"profile_surname,omitempty"`
	ProfilePhotos   *AccountTenant_PhotoFiles `protobuf:"bytes,11,opt,name=profile_photos,json=profilePhotos,proto3,oneof" json:"profile_photos,omitempty"`
	LastLoginAt     *timestamppb.Timestamp    `protobuf:"bytes,13,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	LastRequestAt   *timestamppb.Timestamp    `protobuf:"bytes,14,opt,name=last_request_at,json=lastRequestAt,proto3,oneof" json:"last_request_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountTenant) Reset() {
	*x = AccountTenant{}
	mi := &file_common_types_users_tenant_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTenant) ProtoMessage() {}

func (x *AccountTenant) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_users_tenant_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTenant.ProtoReflect.Descriptor instead.
func (*AccountTenant) Descriptor() ([]byte, []int) {
	return file_common_types_users_tenant_types_proto_rawDescGZIP(), []int{0}
}

func (x *AccountTenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountTenant) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AccountTenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AccountTenant) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AccountTenant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountTenant) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

func (x *AccountTenant) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *AccountTenant) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *AccountTenant) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *AccountTenant) GetProfileSurname() string {
	if x != nil {
		return x.ProfileSurname
	}
	return ""
}

func (x *AccountTenant) GetProfilePhotos() *AccountTenant_PhotoFiles {
	if x != nil {
		return x.ProfilePhotos
	}
	return nil
}

func (x *AccountTenant) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *AccountTenant) GetLastRequestAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequestAt
	}
	return nil
}

type AccountTenant_PhotoFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalFile  *File                  `protobuf:"bytes,1,opt,name=original_file,json=originalFile,proto3" json:"original_file,omitempty"`
	S100X100File  *File                  `protobuf:"bytes,2,opt,name=s100x100_file,json=s100x100File,proto3" json:"s100x100_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTenant_PhotoFiles) Reset() {
	*x = AccountTenant_PhotoFiles{}
	mi := &file_common_types_users_tenant_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTenant_PhotoFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTenant_PhotoFiles) ProtoMessage() {}

func (x *AccountTenant_PhotoFiles) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_users_tenant_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTenant_PhotoFiles.ProtoReflect.Descriptor instead.
func (*AccountTenant_PhotoFiles) Descriptor() ([]byte, []int) {
	return file_common_types_users_tenant_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AccountTenant_PhotoFiles) GetOriginalFile() *File {
	if x != nil {
		return x.OriginalFile
	}
	return nil
}

func (x *AccountTenant_PhotoFiles) GetS100X100File() *File {
	if x != nil {
		return x.S100X100File
	}
	return nil
}

var File_common_types_users_tenant_types_proto protoreflect.FileDescriptor

const file_common_types_users_tenant_types_proto_rawDesc = "" +
	"\n" +
	"%common/types/users_tenant_types.proto\x12\btypes.v1\x1a\x18common/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x05\n" +
	"\rAccountTenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\x04R\x06roleId\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fis_confirmed\x18\x06 \x01(\bR\visConfirmed\x12*\n" +
	"\x11is_email_verified\x18\a \x01(\bR\x0fisEmailVerified\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\b \x01(\bR\tisBlocked\x12!\n" +
	"\fprofile_name\x18\t \x01(\tR\vprofileName\x12'\n" +
	"\x0fprofile_surname\x18\n" +
	" \x01(\tR\x0eprofileSurname\x12N\n" +
	"\x0eprofile_photos\x18\v \x01(\v2\".types.v1.AccountTenant.PhotoFilesH\x00R\rprofilePhotos\x88\x01\x01\x12C\n" +
	"\rlast_login_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vlastLoginAt\x88\x01\x01\x12G\n" +
	"\x0flast_request_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x02R\rlastRequestAt\x88\x01\x01\x1av\n" +
	"\n" +
	"PhotoFiles\x123\n" +
	"\roriginal_file\x18\x01 \x01(\v2\x0e.types.v1.FileR\foriginalFile\x123\n" +
	"\rs100x100_file\x18\x02 \x01(\v2\x0e.types.v1.FileR\fs100x100FileB\x11\n" +
	"\x0f_profile_photosB\x10\n" +
	"\x0e_last_login_atB\x12\n" +
	"\x10_last_request_atB\xa8\x01\n" +
	"\fcom.types.v1B\x15UsersTenantTypesProtoP\x01Z@github.com/neurochar/workflows/pkg/proto_pb/common/types;typesv1\xa2\x02\x03TXX\xaa\x02\bTypes.V1\xca\x02\bTypes\\V1\xe2\x02\x14Types\\V1\\GPBMetadata\xea\x02\tTypes::V1b\x06proto3"

var (
	file_common_types_users_tenant_types_proto_rawDescOnce sync.Once
	file_common_types_users_tenant_types_proto_rawDescData []byte
)

func file_common_types_users_tenant_types_proto_rawDescGZIP() []byte {
	file_common_types_users_tenant_types_proto_rawDescOnce.Do(func() {
		file_common_types_users_tenant_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_users_tenant_types_proto_rawDesc), len(file_common_types_users_tenant_types_proto_rawDesc)))
	})
	return file_common_types_users_tenant_types_proto_rawDescData
}

var file_common_types_users_tenant_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_types_users_tenant_types_proto_goTypes = []any{
	(*AccountTenant)(nil),            // 0: types.v1.AccountTenant
	(*AccountTenant_PhotoFiles)(nil), // 1: types.v1.AccountTenant.PhotoFiles
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
	(*File)(nil),                     // 3: types.v1.File
}
var file_common_types_users_tenant_types_proto_depIdxs = []int32{
	1, // 0: types.v1.AccountTenant.profile_photos:type_name -> types.v1.AccountTenant.PhotoFiles
	2, // 1: types.v1.AccountTenant.last_login_at:type_name -> google.protobuf.Timestamp
	2, // 2: types.v1.AccountTenant.last_request_at:type_name -> google.protobuf.Timestamp
	3, // 3: types.v1.AccountTenant.PhotoFiles.original_file:type_name -> types.v1.File
	3, // 4: types.v1.AccountTenant.PhotoFiles.s100x100_file:type_name -> types.v1.File
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_types_users_tenant_types_proto_init() }
func file_common_types_users_tenant_types_proto_init() {
	if File_common_types_users_tenant_types_proto != nil {
		return
	}
	file_common_types_types_proto_init()
	file_common_types_users_tenant_types_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_users_tenant_types_proto_rawDesc), len(file_common_types_users_tenant_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_users_tenant_types_proto_goTypes,
		DependencyIndexes: file_common_types_users_tenant_types_proto_depIdxs,
		MessageInfos:      file_common_types_users_tenant_types_proto_msgTypes,
	}.Build()
	File_common_types_users_tenant_types_proto = out.File
	file_common_types_users_tenant_types_proto_goTypes = nil
	file_common_types_users_tenant_types_proto_depIdxs = nil
}
