// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/registration/v1/dto.proto

package registrationv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/neurochar/workflows/pkg/proto_pb/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationRequest) Reset() {
	*x = StartRegistrationRequest{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationRequest) ProtoMessage() {}

func (x *StartRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationRequest.ProtoReflect.Descriptor instead.
func (*StartRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{0}
}

func (x *StartRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationResponse) Reset() {
	*x = StartRegistrationResponse{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResponse) ProtoMessage() {}

func (x *StartRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResponse.ProtoReflect.Descriptor instead.
func (*StartRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{1}
}

type FinishRegistrationRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantTextId   string                 `protobuf:"bytes,1,opt,name=tenant_text_id,json=tenantTextId,proto3" json:"tenant_text_id,omitempty"`
	ProfileName    string                 `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	ProfileSurname string                 `protobuf:"bytes,3,opt,name=profile_surname,json=profileSurname,proto3" json:"profile_surname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinishRegistrationRequestPayload) Reset() {
	*x = FinishRegistrationRequestPayload{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationRequestPayload) ProtoMessage() {}

func (x *FinishRegistrationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationRequestPayload.ProtoReflect.Descriptor instead.
func (*FinishRegistrationRequestPayload) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRegistrationRequestPayload) GetTenantTextId() string {
	if x != nil {
		return x.TenantTextId
	}
	return ""
}

func (x *FinishRegistrationRequestPayload) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *FinishRegistrationRequestPayload) GetProfileSurname() string {
	if x != nil {
		return x.ProfileSurname
	}
	return ""
}

type FinishRegistrationRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Id            string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *FinishRegistrationRequestPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationRequest) Reset() {
	*x = FinishRegistrationRequest{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationRequest) ProtoMessage() {}

func (x *FinishRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{3}
}

func (x *FinishRegistrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinishRegistrationRequest) GetPayload() *FinishRegistrationRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type FinishRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TextId        string                 `protobuf:"bytes,2,opt,name=text_id,json=textId,proto3" json:"text_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationResponse) Reset() {
	*x = FinishRegistrationResponse{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResponse) ProtoMessage() {}

func (x *FinishRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{4}
}

func (x *FinishRegistrationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinishRegistrationResponse) GetTextId() string {
	if x != nil {
		return x.TextId
	}
	return ""
}

func (x *FinishRegistrationResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationRequest) Reset() {
	*x = CheckRegistrationRequest{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationRequest) ProtoMessage() {}

func (x *CheckRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CheckRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRegistrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRegistrationResponse) Reset() {
	*x = CheckRegistrationResponse{}
	mi := &file_public_registration_v1_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRegistrationResponse) ProtoMessage() {}

func (x *CheckRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_registration_v1_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CheckRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_public_registration_v1_dto_proto_rawDescGZIP(), []int{6}
}

var File_public_registration_v1_dto_proto protoreflect.FileDescriptor

const file_public_registration_v1_dto_proto_rawDesc = "" +
	"\n" +
	" public/registration/v1/dto.proto\x12\x0fregistration.v1\x1a\x18common/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\x18StartRegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1b\n" +
	"\x19StartRegistrationResponse\"\xb8\x01\n" +
	" FinishRegistrationRequestPayload\x120\n" +
	"\x0etenant_text_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01R\ftenantTextId\x12-\n" +
	"\fprofile_name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01R\vprofileName\x123\n" +
	"\x0fprofile_surname\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01R\x0eprofileSurname\"\x8a\x01\n" +
	"\x19FinishRegistrationRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12S\n" +
	"\apayload\x18\x02 \x01(\v21.registration.v1.FinishRegistrationRequestPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\"W\n" +
	"\x1aFinishRegistrationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atext_id\x18\x02 \x01(\tR\x06textId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"*\n" +
	"\x18CheckRegistrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19CheckRegistrationResponseB\xcf\x01\n" +
	"\x13com.registration.v1B\bDtoProtoP\x01ZQgithub.com/neurochar/workflows/pkg/proto_pb/public/registration/v1;registrationv1\xa2\x02\x03RXX\xaa\x02\x0fRegistration.V1\xca\x02\x0fRegistration\\V1\xe2\x02\x1bRegistration\\V1\\GPBMetadata\xea\x02\x10Registration::V1b\x06proto3"

var (
	file_public_registration_v1_dto_proto_rawDescOnce sync.Once
	file_public_registration_v1_dto_proto_rawDescData []byte
)

func file_public_registration_v1_dto_proto_rawDescGZIP() []byte {
	file_public_registration_v1_dto_proto_rawDescOnce.Do(func() {
		file_public_registration_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_registration_v1_dto_proto_rawDesc), len(file_public_registration_v1_dto_proto_rawDesc)))
	})
	return file_public_registration_v1_dto_proto_rawDescData
}

var file_public_registration_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_public_registration_v1_dto_proto_goTypes = []any{
	(*StartRegistrationRequest)(nil),         // 0: registration.v1.StartRegistrationRequest
	(*StartRegistrationResponse)(nil),        // 1: registration.v1.StartRegistrationResponse
	(*FinishRegistrationRequestPayload)(nil), // 2: registration.v1.FinishRegistrationRequestPayload
	(*FinishRegistrationRequest)(nil),        // 3: registration.v1.FinishRegistrationRequest
	(*FinishRegistrationResponse)(nil),       // 4: registration.v1.FinishRegistrationResponse
	(*CheckRegistrationRequest)(nil),         // 5: registration.v1.CheckRegistrationRequest
	(*CheckRegistrationResponse)(nil),        // 6: registration.v1.CheckRegistrationResponse
}
var file_public_registration_v1_dto_proto_depIdxs = []int32{
	2, // 0: registration.v1.FinishRegistrationRequest.payload:type_name -> registration.v1.FinishRegistrationRequestPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_public_registration_v1_dto_proto_init() }
func file_public_registration_v1_dto_proto_init() {
	if File_public_registration_v1_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_registration_v1_dto_proto_rawDesc), len(file_public_registration_v1_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_registration_v1_dto_proto_goTypes,
		DependencyIndexes: file_public_registration_v1_dto_proto_depIdxs,
		MessageInfos:      file_public_registration_v1_dto_proto_msgTypes,
	}.Build()
	File_public_registration_v1_dto_proto = out.File
	file_public_registration_v1_dto_proto_goTypes = nil
	file_public_registration_v1_dto_proto_depIdxs = nil
}
