// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/registration/v1/service.proto

package registrationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationPublicService_StartRegistration_FullMethodName  = "/registration.v1.RegistrationPublicService/StartRegistration"
	RegistrationPublicService_FinishRegistration_FullMethodName = "/registration.v1.RegistrationPublicService/FinishRegistration"
	RegistrationPublicService_CheckRegistration_FullMethodName  = "/registration.v1.RegistrationPublicService/CheckRegistration"
)

// RegistrationPublicServiceClient is the client API for RegistrationPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrationPublicServiceClient interface {
	// Начать регистрацию
	StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error)
	// Закончить регистрацию
	FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error)
	// Проверить регистрацию
	CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error)
}

type registrationPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationPublicServiceClient(cc grpc.ClientConnInterface) RegistrationPublicServiceClient {
	return &registrationPublicServiceClient{cc}
}

func (c *registrationPublicServiceClient) StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationPublicService_StartRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationPublicServiceClient) FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationPublicService_FinishRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationPublicServiceClient) CheckRegistration(ctx context.Context, in *CheckRegistrationRequest, opts ...grpc.CallOption) (*CheckRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationPublicService_CheckRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationPublicServiceServer is the server API for RegistrationPublicService service.
// All implementations must embed UnimplementedRegistrationPublicServiceServer
// for forward compatibility.
type RegistrationPublicServiceServer interface {
	// Начать регистрацию
	StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error)
	// Закончить регистрацию
	FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error)
	// Проверить регистрацию
	CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error)
	mustEmbedUnimplementedRegistrationPublicServiceServer()
}

// UnimplementedRegistrationPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationPublicServiceServer struct{}

func (UnimplementedRegistrationPublicServiceServer) StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRegistration not implemented")
}
func (UnimplementedRegistrationPublicServiceServer) FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (UnimplementedRegistrationPublicServiceServer) CheckRegistration(context.Context, *CheckRegistrationRequest) (*CheckRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRegistration not implemented")
}
func (UnimplementedRegistrationPublicServiceServer) mustEmbedUnimplementedRegistrationPublicServiceServer() {
}
func (UnimplementedRegistrationPublicServiceServer) testEmbeddedByValue() {}

// UnsafeRegistrationPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationPublicServiceServer will
// result in compilation errors.
type UnsafeRegistrationPublicServiceServer interface {
	mustEmbedUnimplementedRegistrationPublicServiceServer()
}

func RegisterRegistrationPublicServiceServer(s grpc.ServiceRegistrar, srv RegistrationPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistrationPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationPublicService_ServiceDesc, srv)
}

func _RegistrationPublicService_StartRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationPublicServiceServer).StartRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationPublicService_StartRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationPublicServiceServer).StartRegistration(ctx, req.(*StartRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationPublicService_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationPublicServiceServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationPublicService_FinishRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationPublicServiceServer).FinishRegistration(ctx, req.(*FinishRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationPublicService_CheckRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationPublicServiceServer).CheckRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationPublicService_CheckRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationPublicServiceServer).CheckRegistration(ctx, req.(*CheckRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationPublicService_ServiceDesc is the grpc.ServiceDesc for RegistrationPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registration.v1.RegistrationPublicService",
	HandlerType: (*RegistrationPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRegistration",
			Handler:    _RegistrationPublicService_StartRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _RegistrationPublicService_FinishRegistration_Handler,
		},
		{
			MethodName: "CheckRegistration",
			Handler:    _RegistrationPublicService_CheckRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/registration/v1/service.proto",
}
