// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/registration/v1/service.proto

package registrationv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_registration_v1_service_proto protoreflect.FileDescriptor

const file_public_registration_v1_service_proto_rawDesc = "" +
	"\n" +
	"$public/registration/v1/service.proto\x12\x0fregistration.v1\x1a public/registration/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xcb\x03\n" +
	"\x19RegistrationPublicService\x12\x8d\x01\n" +
	"\x11StartRegistration\x12).registration.v1.StartRegistrationRequest\x1a*.registration.v1.StartRegistrationResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/registration/start\x12\x91\x01\n" +
	"\x12FinishRegistration\x12*.registration.v1.FinishRegistrationRequest\x1a+.registration.v1.FinishRegistrationResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/registration/finish\x12\x89\x01\n" +
	"\x11CheckRegistration\x12).registration.v1.CheckRegistrationRequest\x1a*.registration.v1.CheckRegistrationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/registration/{id}B\xd3\x01\n" +
	"\x13com.registration.v1B\fServiceProtoP\x01ZQgithub.com/neurochar/workflows/pkg/proto_pb/public/registration/v1;registrationv1\xa2\x02\x03RXX\xaa\x02\x0fRegistration.V1\xca\x02\x0fRegistration\\V1\xe2\x02\x1bRegistration\\V1\\GPBMetadata\xea\x02\x10Registration::V1b\x06proto3"

var file_public_registration_v1_service_proto_goTypes = []any{
	(*StartRegistrationRequest)(nil),   // 0: registration.v1.StartRegistrationRequest
	(*FinishRegistrationRequest)(nil),  // 1: registration.v1.FinishRegistrationRequest
	(*CheckRegistrationRequest)(nil),   // 2: registration.v1.CheckRegistrationRequest
	(*StartRegistrationResponse)(nil),  // 3: registration.v1.StartRegistrationResponse
	(*FinishRegistrationResponse)(nil), // 4: registration.v1.FinishRegistrationResponse
	(*CheckRegistrationResponse)(nil),  // 5: registration.v1.CheckRegistrationResponse
}
var file_public_registration_v1_service_proto_depIdxs = []int32{
	0, // 0: registration.v1.RegistrationPublicService.StartRegistration:input_type -> registration.v1.StartRegistrationRequest
	1, // 1: registration.v1.RegistrationPublicService.FinishRegistration:input_type -> registration.v1.FinishRegistrationRequest
	2, // 2: registration.v1.RegistrationPublicService.CheckRegistration:input_type -> registration.v1.CheckRegistrationRequest
	3, // 3: registration.v1.RegistrationPublicService.StartRegistration:output_type -> registration.v1.StartRegistrationResponse
	4, // 4: registration.v1.RegistrationPublicService.FinishRegistration:output_type -> registration.v1.FinishRegistrationResponse
	5, // 5: registration.v1.RegistrationPublicService.CheckRegistration:output_type -> registration.v1.CheckRegistrationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_registration_v1_service_proto_init() }
func file_public_registration_v1_service_proto_init() {
	if File_public_registration_v1_service_proto != nil {
		return
	}
	file_public_registration_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_registration_v1_service_proto_rawDesc), len(file_public_registration_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_registration_v1_service_proto_goTypes,
		DependencyIndexes: file_public_registration_v1_service_proto_depIdxs,
	}.Build()
	File_public_registration_v1_service_proto = out.File
	file_public_registration_v1_service_proto_goTypes = nil
	file_public_registration_v1_service_proto_depIdxs = nil
}
