// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/crm/v1/dto.proto

package crmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/neurochar/workflows/pkg/proto_pb/common/types"
	_ "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *uint64                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint64                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	SearchQuery   *string                `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3,oneof" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesRequest) Reset() {
	*x = ListCandidatesRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesRequest) ProtoMessage() {}

func (x *ListCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{0}
}

func (x *ListCandidatesRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListCandidatesRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListCandidatesRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

type ListCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*types.ListCandidate `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesResponse) Reset() {
	*x = ListCandidatesResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesResponse) ProtoMessage() {}

func (x *ListCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ListCandidatesResponse) GetItems() []*types.ListCandidate {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCandidatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateRequest) Reset() {
	*x = GetCandidateRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateRequest) ProtoMessage() {}

func (x *GetCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *types.Candidate       `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateResponse) Reset() {
	*x = GetCandidateResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateResponse) ProtoMessage() {}

func (x *GetCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidateResponse) GetItem() *types.Candidate {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateCandidateRequestPayload struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Name          string                                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                                     `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender        types.Gender                               `protobuf:"varint,3,opt,name=gender,proto3,enum=types.v1.Gender" json:"gender,omitempty"`
	Birthday      *types.OptionalDate                        `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	ResumeFiles   *CreateCandidateRequestPayload_ResumeFiles `protobuf:"bytes,5,opt,name=resume_files,json=resumeFiles,proto3,oneof" json:"resume_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequestPayload) Reset() {
	*x = CreateCandidateRequestPayload{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequestPayload) ProtoMessage() {}

func (x *CreateCandidateRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequestPayload) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCandidateRequestPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCandidateRequestPayload) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *CreateCandidateRequestPayload) GetGender() types.Gender {
	if x != nil {
		return x.Gender
	}
	return types.Gender(0)
}

func (x *CreateCandidateRequestPayload) GetBirthday() *types.OptionalDate {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *CreateCandidateRequestPayload) GetResumeFiles() *CreateCandidateRequestPayload_ResumeFiles {
	if x != nil {
		return x.ResumeFiles
	}
	return nil
}

type CreateCandidateRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payload       *CreateCandidateRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCandidateRequest) GetPayload() *CreateCandidateRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *types.Candidate       `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateResponse) Reset() {
	*x = CreateCandidateResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateResponse) ProtoMessage() {}

func (x *CreateCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateResponse.ProtoReflect.Descriptor instead.
func (*CreateCandidateResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCandidateResponse) GetItem() *types.Candidate {
	if x != nil {
		return x.Item
	}
	return nil
}

type PatchCandidateRequestPayload struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Surname  *string                `protobuf:"bytes,2,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	Gender   *types.Gender          `protobuf:"varint,3,opt,name=gender,proto3,enum=types.v1.Gender,oneof" json:"gender,omitempty"`
	Birthday *types.OptionalDate    `protobuf:"bytes,4,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	// Types that are valid to be assigned to ResumeFilesAction:
	//
	//	*PatchCandidateRequestPayload_ResumeFiles_
	//	*PatchCandidateRequestPayload_ResumeFilesClear
	ResumeFilesAction isPatchCandidateRequestPayload_ResumeFilesAction `protobuf_oneof:"resume_files_action"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PatchCandidateRequestPayload) Reset() {
	*x = PatchCandidateRequestPayload{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidateRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidateRequestPayload) ProtoMessage() {}

func (x *PatchCandidateRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidateRequestPayload.ProtoReflect.Descriptor instead.
func (*PatchCandidateRequestPayload) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{7}
}

func (x *PatchCandidateRequestPayload) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PatchCandidateRequestPayload) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *PatchCandidateRequestPayload) GetGender() types.Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return types.Gender(0)
}

func (x *PatchCandidateRequestPayload) GetBirthday() *types.OptionalDate {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *PatchCandidateRequestPayload) GetResumeFilesAction() isPatchCandidateRequestPayload_ResumeFilesAction {
	if x != nil {
		return x.ResumeFilesAction
	}
	return nil
}

func (x *PatchCandidateRequestPayload) GetResumeFiles() *PatchCandidateRequestPayload_ResumeFiles {
	if x != nil {
		if x, ok := x.ResumeFilesAction.(*PatchCandidateRequestPayload_ResumeFiles_); ok {
			return x.ResumeFiles
		}
	}
	return nil
}

func (x *PatchCandidateRequestPayload) GetResumeFilesClear() bool {
	if x != nil {
		if x, ok := x.ResumeFilesAction.(*PatchCandidateRequestPayload_ResumeFilesClear); ok {
			return x.ResumeFilesClear
		}
	}
	return false
}

type isPatchCandidateRequestPayload_ResumeFilesAction interface {
	isPatchCandidateRequestPayload_ResumeFilesAction()
}

type PatchCandidateRequestPayload_ResumeFiles_ struct {
	ResumeFiles *PatchCandidateRequestPayload_ResumeFiles `protobuf:"bytes,6,opt,name=resume_files,json=resumeFiles,proto3,oneof"`
}

type PatchCandidateRequestPayload_ResumeFilesClear struct {
	ResumeFilesClear bool `protobuf:"varint,7,opt,name=resume_files_clear,json=resumeFilesClear,proto3,oneof"`
}

func (*PatchCandidateRequestPayload_ResumeFiles_) isPatchCandidateRequestPayload_ResumeFilesAction() {
}

func (*PatchCandidateRequestPayload_ResumeFilesClear) isPatchCandidateRequestPayload_ResumeFilesAction() {
}

type PatchCandidateRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Id               string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload          *PatchCandidateRequestPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Version          int64                         `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	SkipVersionCheck bool                          `protobuf:"varint,4,opt,name=skip_version_check,json=skipVersionCheck,proto3" json:"skip_version_check,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PatchCandidateRequest) Reset() {
	*x = PatchCandidateRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidateRequest) ProtoMessage() {}

func (x *PatchCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidateRequest.ProtoReflect.Descriptor instead.
func (*PatchCandidateRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{8}
}

func (x *PatchCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchCandidateRequest) GetPayload() *PatchCandidateRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PatchCandidateRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PatchCandidateRequest) GetSkipVersionCheck() bool {
	if x != nil {
		return x.SkipVersionCheck
	}
	return false
}

type PatchCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidateResponse) Reset() {
	*x = PatchCandidateResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidateResponse) ProtoMessage() {}

func (x *PatchCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidateResponse.ProtoReflect.Descriptor instead.
func (*PatchCandidateResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{9}
}

type DeleteCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateRequest) Reset() {
	*x = DeleteCandidateRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateRequest) ProtoMessage() {}

func (x *DeleteCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateRequest.ProtoReflect.Descriptor instead.
func (*DeleteCandidateRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCandidateResponse) Reset() {
	*x = DeleteCandidateResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCandidateResponse) ProtoMessage() {}

func (x *DeleteCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCandidateResponse.ProtoReflect.Descriptor instead.
func (*DeleteCandidateResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{11}
}

type UploadCandidateResumeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCandidateResumeFileRequest) Reset() {
	*x = UploadCandidateResumeFileRequest{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCandidateResumeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCandidateResumeFileRequest) ProtoMessage() {}

func (x *UploadCandidateResumeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCandidateResumeFileRequest.ProtoReflect.Descriptor instead.
func (*UploadCandidateResumeFileRequest) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{12}
}

func (x *UploadCandidateResumeFileRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadCandidateResumeFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadCandidateResumeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *types.FilesMap        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCandidateResumeFileResponse) Reset() {
	*x = UploadCandidateResumeFileResponse{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCandidateResumeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCandidateResumeFileResponse) ProtoMessage() {}

func (x *UploadCandidateResumeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCandidateResumeFileResponse.ProtoReflect.Descriptor instead.
func (*UploadCandidateResumeFileResponse) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{13}
}

func (x *UploadCandidateResumeFileResponse) GetData() *types.FilesMap {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCandidateRequestPayload_ResumeFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequestPayload_ResumeFiles) Reset() {
	*x = CreateCandidateRequestPayload_ResumeFiles{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequestPayload_ResumeFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequestPayload_ResumeFiles) ProtoMessage() {}

func (x *CreateCandidateRequestPayload_ResumeFiles) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequestPayload_ResumeFiles.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequestPayload_ResumeFiles) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateCandidateRequestPayload_ResumeFiles) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type PatchCandidateRequestPayload_ResumeFiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchCandidateRequestPayload_ResumeFiles) Reset() {
	*x = PatchCandidateRequestPayload_ResumeFiles{}
	mi := &file_public_crm_v1_dto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchCandidateRequestPayload_ResumeFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchCandidateRequestPayload_ResumeFiles) ProtoMessage() {}

func (x *PatchCandidateRequestPayload_ResumeFiles) ProtoReflect() protoreflect.Message {
	mi := &file_public_crm_v1_dto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchCandidateRequestPayload_ResumeFiles.ProtoReflect.Descriptor instead.
func (*PatchCandidateRequestPayload_ResumeFiles) Descriptor() ([]byte, []int) {
	return file_public_crm_v1_dto_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PatchCandidateRequestPayload_ResumeFiles) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

var File_public_crm_v1_dto_proto protoreflect.FileDescriptor

const file_public_crm_v1_dto_proto_rawDesc = "" +
	"\n" +
	"\x17public/crm/v1/dto.proto\x12\x06crm.v1\x1a\x18common/types/types.proto\x1a\x1ccommon/types/crm_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a\x16google/type/date.proto\"\x9d\x01\n" +
	"\x15ListCandidatesRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x04H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x04H\x01R\x06offset\x88\x01\x01\x12&\n" +
	"\fsearch_query\x18\x03 \x01(\tH\x02R\vsearchQuery\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x0f\n" +
	"\r_search_query\"]\n" +
	"\x16ListCandidatesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.types.v1.ListCandidateR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x13GetCandidateRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"?\n" +
	"\x14GetCandidateResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.types.v1.CandidateR\x04item\"\xe1\x02\n" +
	"\x1dCreateCandidateRequestPayload\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01R\x04name\x12$\n" +
	"\asurname\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01R\asurname\x12(\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x10.types.v1.GenderR\x06gender\x122\n" +
	"\bbirthday\x18\x04 \x01(\v2\x16.types.v1.OptionalDateR\bbirthday\x12Y\n" +
	"\fresume_files\x18\x05 \x01(\v21.crm.v1.CreateCandidateRequestPayload.ResumeFilesH\x00R\vresumeFiles\x88\x01\x01\x1a0\n" +
	"\vResumeFiles\x12!\n" +
	"\afile_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06fileIdB\x0f\n" +
	"\r_resume_files\"a\n" +
	"\x16CreateCandidateRequest\x12G\n" +
	"\apayload\x18\x01 \x01(\v2%.crm.v1.CreateCandidateRequestPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\"B\n" +
	"\x17CreateCandidateResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.types.v1.CandidateR\x04item\"\xd3\x03\n" +
	"\x1cPatchCandidateRequestPayload\x12#\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01H\x01R\x04name\x88\x01\x01\x12)\n" +
	"\asurname\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x96\x01H\x02R\asurname\x88\x01\x01\x12-\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x10.types.v1.GenderH\x03R\x06gender\x88\x01\x01\x127\n" +
	"\bbirthday\x18\x04 \x01(\v2\x16.types.v1.OptionalDateH\x04R\bbirthday\x88\x01\x01\x12U\n" +
	"\fresume_files\x18\x06 \x01(\v20.crm.v1.PatchCandidateRequestPayload.ResumeFilesH\x00R\vresumeFiles\x12.\n" +
	"\x12resume_files_clear\x18\a \x01(\bH\x00R\x10resumeFilesClear\x1a0\n" +
	"\vResumeFiles\x12!\n" +
	"\afile_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06fileIdB\x15\n" +
	"\x13resume_files_actionB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_surnameB\t\n" +
	"\a_genderB\v\n" +
	"\t_birthday\"\xc1\x01\n" +
	"\x15PatchCandidateRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12F\n" +
	"\apayload\x18\x02 \x01(\v2$.crm.v1.PatchCandidateRequestPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12,\n" +
	"\x12skip_version_check\x18\x04 \x01(\bR\x10skipVersionCheck\"\x18\n" +
	"\x16PatchCandidateResponse\"2\n" +
	"\x16DeleteCandidateRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x19\n" +
	"\x17DeleteCandidateResponse\"R\n" +
	" UploadCandidateResumeFileRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"K\n" +
	"!UploadCandidateResumeFileResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.types.v1.FilesMapR\x04dataB\x90\x01\n" +
	"\n" +
	"com.crm.v1B\bDtoProtoP\x01Z?github.com/neurochar/workflows/pkg/proto_pb/public/crm/v1;crmv1\xa2\x02\x03CXX\xaa\x02\x06Crm.V1\xca\x02\x06Crm\\V1\xe2\x02\x12Crm\\V1\\GPBMetadata\xea\x02\aCrm::V1b\x06proto3"

var (
	file_public_crm_v1_dto_proto_rawDescOnce sync.Once
	file_public_crm_v1_dto_proto_rawDescData []byte
)

func file_public_crm_v1_dto_proto_rawDescGZIP() []byte {
	file_public_crm_v1_dto_proto_rawDescOnce.Do(func() {
		file_public_crm_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_crm_v1_dto_proto_rawDesc), len(file_public_crm_v1_dto_proto_rawDesc)))
	})
	return file_public_crm_v1_dto_proto_rawDescData
}

var file_public_crm_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_public_crm_v1_dto_proto_goTypes = []any{
	(*ListCandidatesRequest)(nil),                     // 0: crm.v1.ListCandidatesRequest
	(*ListCandidatesResponse)(nil),                    // 1: crm.v1.ListCandidatesResponse
	(*GetCandidateRequest)(nil),                       // 2: crm.v1.GetCandidateRequest
	(*GetCandidateResponse)(nil),                      // 3: crm.v1.GetCandidateResponse
	(*CreateCandidateRequestPayload)(nil),             // 4: crm.v1.CreateCandidateRequestPayload
	(*CreateCandidateRequest)(nil),                    // 5: crm.v1.CreateCandidateRequest
	(*CreateCandidateResponse)(nil),                   // 6: crm.v1.CreateCandidateResponse
	(*PatchCandidateRequestPayload)(nil),              // 7: crm.v1.PatchCandidateRequestPayload
	(*PatchCandidateRequest)(nil),                     // 8: crm.v1.PatchCandidateRequest
	(*PatchCandidateResponse)(nil),                    // 9: crm.v1.PatchCandidateResponse
	(*DeleteCandidateRequest)(nil),                    // 10: crm.v1.DeleteCandidateRequest
	(*DeleteCandidateResponse)(nil),                   // 11: crm.v1.DeleteCandidateResponse
	(*UploadCandidateResumeFileRequest)(nil),          // 12: crm.v1.UploadCandidateResumeFileRequest
	(*UploadCandidateResumeFileResponse)(nil),         // 13: crm.v1.UploadCandidateResumeFileResponse
	(*CreateCandidateRequestPayload_ResumeFiles)(nil), // 14: crm.v1.CreateCandidateRequestPayload.ResumeFiles
	(*PatchCandidateRequestPayload_ResumeFiles)(nil),  // 15: crm.v1.PatchCandidateRequestPayload.ResumeFiles
	(*types.ListCandidate)(nil),                       // 16: types.v1.ListCandidate
	(*types.Candidate)(nil),                           // 17: types.v1.Candidate
	(types.Gender)(0),                                 // 18: types.v1.Gender
	(*types.OptionalDate)(nil),                        // 19: types.v1.OptionalDate
	(*types.FilesMap)(nil),                            // 20: types.v1.FilesMap
}
var file_public_crm_v1_dto_proto_depIdxs = []int32{
	16, // 0: crm.v1.ListCandidatesResponse.items:type_name -> types.v1.ListCandidate
	17, // 1: crm.v1.GetCandidateResponse.item:type_name -> types.v1.Candidate
	18, // 2: crm.v1.CreateCandidateRequestPayload.gender:type_name -> types.v1.Gender
	19, // 3: crm.v1.CreateCandidateRequestPayload.birthday:type_name -> types.v1.OptionalDate
	14, // 4: crm.v1.CreateCandidateRequestPayload.resume_files:type_name -> crm.v1.CreateCandidateRequestPayload.ResumeFiles
	4,  // 5: crm.v1.CreateCandidateRequest.payload:type_name -> crm.v1.CreateCandidateRequestPayload
	17, // 6: crm.v1.CreateCandidateResponse.item:type_name -> types.v1.Candidate
	18, // 7: crm.v1.PatchCandidateRequestPayload.gender:type_name -> types.v1.Gender
	19, // 8: crm.v1.PatchCandidateRequestPayload.birthday:type_name -> types.v1.OptionalDate
	15, // 9: crm.v1.PatchCandidateRequestPayload.resume_files:type_name -> crm.v1.PatchCandidateRequestPayload.ResumeFiles
	7,  // 10: crm.v1.PatchCandidateRequest.payload:type_name -> crm.v1.PatchCandidateRequestPayload
	20, // 11: crm.v1.UploadCandidateResumeFileResponse.data:type_name -> types.v1.FilesMap
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_public_crm_v1_dto_proto_init() }
func file_public_crm_v1_dto_proto_init() {
	if File_public_crm_v1_dto_proto != nil {
		return
	}
	file_public_crm_v1_dto_proto_msgTypes[0].OneofWrappers = []any{}
	file_public_crm_v1_dto_proto_msgTypes[4].OneofWrappers = []any{}
	file_public_crm_v1_dto_proto_msgTypes[7].OneofWrappers = []any{
		(*PatchCandidateRequestPayload_ResumeFiles_)(nil),
		(*PatchCandidateRequestPayload_ResumeFilesClear)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_crm_v1_dto_proto_rawDesc), len(file_public_crm_v1_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_crm_v1_dto_proto_goTypes,
		DependencyIndexes: file_public_crm_v1_dto_proto_depIdxs,
		MessageInfos:      file_public_crm_v1_dto_proto_msgTypes,
	}.Build()
	File_public_crm_v1_dto_proto = out.File
	file_public_crm_v1_dto_proto_goTypes = nil
	file_public_crm_v1_dto_proto_depIdxs = nil
}
