// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/crm/v1/service.proto

package crmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrmPublicService_ListCandidates_FullMethodName            = "/crm.v1.CrmPublicService/ListCandidates"
	CrmPublicService_GetCandidate_FullMethodName              = "/crm.v1.CrmPublicService/GetCandidate"
	CrmPublicService_CreateCandidate_FullMethodName           = "/crm.v1.CrmPublicService/CreateCandidate"
	CrmPublicService_PatchCandidate_FullMethodName            = "/crm.v1.CrmPublicService/PatchCandidate"
	CrmPublicService_DeleteCandidate_FullMethodName           = "/crm.v1.CrmPublicService/DeleteCandidate"
	CrmPublicService_UploadCandidateResumeFile_FullMethodName = "/crm.v1.CrmPublicService/UploadCandidateResumeFile"
)

// CrmPublicServiceClient is the client API for CrmPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrmPublicServiceClient interface {
	// Список кандидатов
	ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error)
	// Получить кандидата
	GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error)
	// Создать кандидата
	CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error)
	// Обновить кандидата
	PatchCandidate(ctx context.Context, in *PatchCandidateRequest, opts ...grpc.CallOption) (*PatchCandidateResponse, error)
	// Удалить кандидата
	DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error)
	// Загрузить файл-резюме кандидата
	UploadCandidateResumeFile(ctx context.Context, in *UploadCandidateResumeFileRequest, opts ...grpc.CallOption) (*UploadCandidateResumeFileResponse, error)
}

type crmPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrmPublicServiceClient(cc grpc.ClientConnInterface) CrmPublicServiceClient {
	return &crmPublicServiceClient{cc}
}

func (c *crmPublicServiceClient) ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCandidatesResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_ListCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmPublicServiceClient) GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmPublicServiceClient) CreateCandidate(ctx context.Context, in *CreateCandidateRequest, opts ...grpc.CallOption) (*CreateCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCandidateResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_CreateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmPublicServiceClient) PatchCandidate(ctx context.Context, in *PatchCandidateRequest, opts ...grpc.CallOption) (*PatchCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchCandidateResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_PatchCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmPublicServiceClient) DeleteCandidate(ctx context.Context, in *DeleteCandidateRequest, opts ...grpc.CallOption) (*DeleteCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCandidateResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_DeleteCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crmPublicServiceClient) UploadCandidateResumeFile(ctx context.Context, in *UploadCandidateResumeFileRequest, opts ...grpc.CallOption) (*UploadCandidateResumeFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadCandidateResumeFileResponse)
	err := c.cc.Invoke(ctx, CrmPublicService_UploadCandidateResumeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrmPublicServiceServer is the server API for CrmPublicService service.
// All implementations must embed UnimplementedCrmPublicServiceServer
// for forward compatibility.
type CrmPublicServiceServer interface {
	// Список кандидатов
	ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error)
	// Получить кандидата
	GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error)
	// Создать кандидата
	CreateCandidate(context.Context, *CreateCandidateRequest) (*CreateCandidateResponse, error)
	// Обновить кандидата
	PatchCandidate(context.Context, *PatchCandidateRequest) (*PatchCandidateResponse, error)
	// Удалить кандидата
	DeleteCandidate(context.Context, *DeleteCandidateRequest) (*DeleteCandidateResponse, error)
	// Загрузить файл-резюме кандидата
	UploadCandidateResumeFile(context.Context, *UploadCandidateResumeFileRequest) (*UploadCandidateResumeFileResponse, error)
	mustEmbedUnimplementedCrmPublicServiceServer()
}

// UnimplementedCrmPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrmPublicServiceServer struct{}

func (UnimplementedCrmPublicServiceServer) ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCandidates not implemented")
}
func (UnimplementedCrmPublicServiceServer) GetCandidate(context.Context, *GetCandidateRequest) (*GetCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedCrmPublicServiceServer) CreateCandidate(context.Context, *CreateCandidateRequest) (*CreateCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (UnimplementedCrmPublicServiceServer) PatchCandidate(context.Context, *PatchCandidateRequest) (*PatchCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchCandidate not implemented")
}
func (UnimplementedCrmPublicServiceServer) DeleteCandidate(context.Context, *DeleteCandidateRequest) (*DeleteCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (UnimplementedCrmPublicServiceServer) UploadCandidateResumeFile(context.Context, *UploadCandidateResumeFileRequest) (*UploadCandidateResumeFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadCandidateResumeFile not implemented")
}
func (UnimplementedCrmPublicServiceServer) mustEmbedUnimplementedCrmPublicServiceServer() {}
func (UnimplementedCrmPublicServiceServer) testEmbeddedByValue()                          {}

// UnsafeCrmPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrmPublicServiceServer will
// result in compilation errors.
type UnsafeCrmPublicServiceServer interface {
	mustEmbedUnimplementedCrmPublicServiceServer()
}

func RegisterCrmPublicServiceServer(s grpc.ServiceRegistrar, srv CrmPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedCrmPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrmPublicService_ServiceDesc, srv)
}

func _CrmPublicService_ListCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).ListCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_ListCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).ListCandidates(ctx, req.(*ListCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmPublicService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).GetCandidate(ctx, req.(*GetCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmPublicService_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_CreateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).CreateCandidate(ctx, req.(*CreateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmPublicService_PatchCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).PatchCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_PatchCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).PatchCandidate(ctx, req.(*PatchCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmPublicService_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_DeleteCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).DeleteCandidate(ctx, req.(*DeleteCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrmPublicService_UploadCandidateResumeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCandidateResumeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmPublicServiceServer).UploadCandidateResumeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmPublicService_UploadCandidateResumeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmPublicServiceServer).UploadCandidateResumeFile(ctx, req.(*UploadCandidateResumeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrmPublicService_ServiceDesc is the grpc.ServiceDesc for CrmPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrmPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crm.v1.CrmPublicService",
	HandlerType: (*CrmPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCandidates",
			Handler:    _CrmPublicService_ListCandidates_Handler,
		},
		{
			MethodName: "GetCandidate",
			Handler:    _CrmPublicService_GetCandidate_Handler,
		},
		{
			MethodName: "CreateCandidate",
			Handler:    _CrmPublicService_CreateCandidate_Handler,
		},
		{
			MethodName: "PatchCandidate",
			Handler:    _CrmPublicService_PatchCandidate_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _CrmPublicService_DeleteCandidate_Handler,
		},
		{
			MethodName: "UploadCandidateResumeFile",
			Handler:    _CrmPublicService_UploadCandidateResumeFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/crm/v1/service.proto",
}
