// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workers/ocr/ocr.proto

package ocrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMsg_Start
	//	*ClientMsg_Chunk
	//	*ClientMsg_End
	//	*ClientMsg_Ping
	Payload       isClientMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMsg) GetPayload() isClientMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMsg) GetStart() *Start {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientMsg) GetChunk() *PdfChunk {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ClientMsg) GetEnd() *End {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *ClientMsg) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMsg_Payload interface {
	isClientMsg_Payload()
}

type ClientMsg_Start struct {
	Start *Start `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientMsg_Chunk struct {
	Chunk *PdfChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ClientMsg_End struct {
	End *End `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

type ClientMsg_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ClientMsg_Start) isClientMsg_Payload() {}

func (*ClientMsg_Chunk) isClientMsg_Payload() {}

func (*ClientMsg_End) isClientMsg_Payload() {}

func (*ClientMsg_Ping) isClientMsg_Payload() {}

type ServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMsg_Ready
	//	*ServerMsg_Pong
	//	*ServerMsg_Progress
	//	*ServerMsg_Result
	//	*ServerMsg_Error
	Payload       isServerMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMsg) GetPayload() isServerMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMsg) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ServerMsg) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMsg) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ServerMsg) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerMsg) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMsg_Payload interface {
	isServerMsg_Payload()
}

type ServerMsg_Ready struct {
	Ready *Ready `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ServerMsg_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type ServerMsg_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ServerMsg_Result struct {
	Result *Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ServerMsg_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ServerMsg_Ready) isServerMsg_Payload() {}

func (*ServerMsg_Pong) isServerMsg_Payload() {}

func (*ServerMsg_Progress) isServerMsg_Payload() {}

func (*ServerMsg_Result) isServerMsg_Payload() {}

func (*ServerMsg_Error) isServerMsg_Payload() {}

type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Dpi           int32                  `protobuf:"varint,4,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Device        string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{2}
}

func (x *Start) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Start) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Start) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Start) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *Start) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type PdfChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfChunk) Reset() {
	*x = PdfChunk{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfChunk) ProtoMessage() {}

func (x *PdfChunk) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfChunk.ProtoReflect.Descriptor instead.
func (*PdfChunk) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{3}
}

func (x *PdfChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type End struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *End) Reset() {
	*x = End{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{4}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ping) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Gpu           bool                   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{6}
}

func (x *Ready) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Ready) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *Ready) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{7}
}

func (x *Pong) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pong) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	PagesDone     int32                  `protobuf:"varint,2,opt,name=pages_done,json=pagesDone,proto3" json:"pages_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{8}
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetPagesDone() int32 {
	if x != nil {
		return x.PagesDone
	}
	return 0
}

type Result struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Engine            string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	Gpu               bool                   `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Device            string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Dpi               int32                  `protobuf:"varint,5,opt,name=dpi,proto3" json:"dpi,omitempty"`
	Languages         []string               `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	PagesText         []string               `protobuf:"bytes,7,rep,name=pages_text,json=pagesText,proto3" json:"pages_text,omitempty"`
	Filename          string                 `protobuf:"bytes,8,opt,name=filename,proto3" json:"filename,omitempty"`
	ProcessDurationMs int64                  `protobuf:"varint,9,opt,name=process_duration_ms,json=processDurationMs,proto3" json:"process_duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Result) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Result) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *Result) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Result) GetDpi() int32 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *Result) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Result) GetPagesText() []string {
	if x != nil {
		return x.PagesText
	}
	return nil
}

func (x *Result) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Result) GetProcessDurationMs() int64 {
	if x != nil {
		return x.ProcessDurationMs
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_workers_ocr_ocr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_workers_ocr_ocr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_workers_ocr_ocr_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workers_ocr_ocr_proto protoreflect.FileDescriptor

const file_workers_ocr_ocr_proto_rawDesc = "" +
	"\n" +
	"\x15workers/ocr/ocr.proto\x12\x06ocr.v1\"\xac\x01\n" +
	"\tClientMsg\x12%\n" +
	"\x05start\x18\x01 \x01(\v2\r.ocr.v1.StartH\x00R\x05start\x12(\n" +
	"\x05chunk\x18\x02 \x01(\v2\x10.ocr.v1.PdfChunkH\x00R\x05chunk\x12\x1f\n" +
	"\x03end\x18\x03 \x01(\v2\v.ocr.v1.EndH\x00R\x03end\x12\"\n" +
	"\x04ping\x18\x04 \x01(\v2\f.ocr.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xe2\x01\n" +
	"\tServerMsg\x12%\n" +
	"\x05ready\x18\x01 \x01(\v2\r.ocr.v1.ReadyH\x00R\x05ready\x12\"\n" +
	"\x04pong\x18\x02 \x01(\v2\f.ocr.v1.PongH\x00R\x04pong\x12.\n" +
	"\bprogress\x18\x03 \x01(\v2\x10.ocr.v1.ProgressH\x00R\bprogress\x12(\n" +
	"\x06result\x18\x04 \x01(\v2\x0e.ocr.v1.ResultH\x00R\x06result\x12%\n" +
	"\x05error\x18\x05 \x01(\v2\r.ocr.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\x05Start\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x10\n" +
	"\x03dpi\x18\x04 \x01(\x05R\x03dpi\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\"\x1e\n" +
	"\bPdfChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x05\n" +
	"\x03End\"+\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"P\n" +
	"\x05Ready\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x10\n" +
	"\x03gpu\x18\x02 \x01(\bR\x03gpu\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"+\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"?\n" +
	"\bProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1d\n" +
	"\n" +
	"pages_done\x18\x02 \x01(\x05R\tpagesDone\"\x84\x02\n" +
	"\x06Result\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\bR\x03gpu\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x10\n" +
	"\x03dpi\x18\x05 \x01(\x05R\x03dpi\x12\x1c\n" +
	"\tlanguages\x18\x06 \x03(\tR\tlanguages\x12\x1d\n" +
	"\n" +
	"pages_text\x18\a \x03(\tR\tpagesText\x12\x1a\n" +
	"\bfilename\x18\b \x01(\tR\bfilename\x12.\n" +
	"\x13process_duration_ms\x18\t \x01(\x03R\x11processDurationMs\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2I\n" +
	"\n" +
	"OcrService\x12;\n" +
	"\x0fExtractTextBidi\x12\x11.ocr.v1.ClientMsg\x1a\x11.ocr.v1.ServerMsg(\x010\x01B\x8e\x01\n" +
	"\n" +
	"com.ocr.v1B\bOcrProtoP\x01Z=github.com/neurochar/workflows/pkg/proto_pb/workers/ocr;ocrv1\xa2\x02\x03OXX\xaa\x02\x06Ocr.V1\xca\x02\x06Ocr\\V1\xe2\x02\x12Ocr\\V1\\GPBMetadata\xea\x02\aOcr::V1b\x06proto3"

var (
	file_workers_ocr_ocr_proto_rawDescOnce sync.Once
	file_workers_ocr_ocr_proto_rawDescData []byte
)

func file_workers_ocr_ocr_proto_rawDescGZIP() []byte {
	file_workers_ocr_ocr_proto_rawDescOnce.Do(func() {
		file_workers_ocr_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_ocr_ocr_proto_rawDesc), len(file_workers_ocr_ocr_proto_rawDesc)))
	})
	return file_workers_ocr_ocr_proto_rawDescData
}

var file_workers_ocr_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_workers_ocr_ocr_proto_goTypes = []any{
	(*ClientMsg)(nil), // 0: ocr.v1.ClientMsg
	(*ServerMsg)(nil), // 1: ocr.v1.ServerMsg
	(*Start)(nil),     // 2: ocr.v1.Start
	(*PdfChunk)(nil),  // 3: ocr.v1.PdfChunk
	(*End)(nil),       // 4: ocr.v1.End
	(*Ping)(nil),      // 5: ocr.v1.Ping
	(*Ready)(nil),     // 6: ocr.v1.Ready
	(*Pong)(nil),      // 7: ocr.v1.Pong
	(*Progress)(nil),  // 8: ocr.v1.Progress
	(*Result)(nil),    // 9: ocr.v1.Result
	(*Error)(nil),     // 10: ocr.v1.Error
}
var file_workers_ocr_ocr_proto_depIdxs = []int32{
	2,  // 0: ocr.v1.ClientMsg.start:type_name -> ocr.v1.Start
	3,  // 1: ocr.v1.ClientMsg.chunk:type_name -> ocr.v1.PdfChunk
	4,  // 2: ocr.v1.ClientMsg.end:type_name -> ocr.v1.End
	5,  // 3: ocr.v1.ClientMsg.ping:type_name -> ocr.v1.Ping
	6,  // 4: ocr.v1.ServerMsg.ready:type_name -> ocr.v1.Ready
	7,  // 5: ocr.v1.ServerMsg.pong:type_name -> ocr.v1.Pong
	8,  // 6: ocr.v1.ServerMsg.progress:type_name -> ocr.v1.Progress
	9,  // 7: ocr.v1.ServerMsg.result:type_name -> ocr.v1.Result
	10, // 8: ocr.v1.ServerMsg.error:type_name -> ocr.v1.Error
	0,  // 9: ocr.v1.OcrService.ExtractTextBidi:input_type -> ocr.v1.ClientMsg
	1,  // 10: ocr.v1.OcrService.ExtractTextBidi:output_type -> ocr.v1.ServerMsg
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_workers_ocr_ocr_proto_init() }
func file_workers_ocr_ocr_proto_init() {
	if File_workers_ocr_ocr_proto != nil {
		return
	}
	file_workers_ocr_ocr_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMsg_Start)(nil),
		(*ClientMsg_Chunk)(nil),
		(*ClientMsg_End)(nil),
		(*ClientMsg_Ping)(nil),
	}
	file_workers_ocr_ocr_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMsg_Ready)(nil),
		(*ServerMsg_Pong)(nil),
		(*ServerMsg_Progress)(nil),
		(*ServerMsg_Result)(nil),
		(*ServerMsg_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_ocr_ocr_proto_rawDesc), len(file_workers_ocr_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workers_ocr_ocr_proto_goTypes,
		DependencyIndexes: file_workers_ocr_ocr_proto_depIdxs,
		MessageInfos:      file_workers_ocr_ocr_proto_msgTypes,
	}.Build()
	File_workers_ocr_ocr_proto = out.File
	file_workers_ocr_ocr_proto_goTypes = nil
	file_workers_ocr_ocr_proto_depIdxs = nil
}
