// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/tenant/v1/service.proto

package tenantv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_tenant_v1_service_proto protoreflect.FileDescriptor

const file_public_tenant_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1epublic/tenant/v1/service.proto\x12\ttenant.v1\x1a\x1apublic/tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x81\x02\n" +
	"\x13TenantPublicService\x12k\n" +
	"\bIsExists\x12\x1a.tenant.v1.IsExistsRequest\x1a\x1b.tenant.v1.IsExistsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/tenant/is-exists/{text_id}\x12}\n" +
	"\vPatchTenant\x12\x1d.tenant.v1.PatchTenantRequest\x1a\x1e.tenant.v1.PatchTenantResponse\"/\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/tenant/{id}B\xa9\x01\n" +
	"\rcom.tenant.v1B\fServiceProtoP\x01ZEgithub.com/neurochar/workflows/pkg/proto_pb/public/tenant/v1;tenantv1\xa2\x02\x03TXX\xaa\x02\tTenant.V1\xca\x02\tTenant\\V1\xe2\x02\x15Tenant\\V1\\GPBMetadata\xea\x02\n" +
	"Tenant::V1b\x06proto3"

var file_public_tenant_v1_service_proto_goTypes = []any{
	(*IsExistsRequest)(nil),     // 0: tenant.v1.IsExistsRequest
	(*PatchTenantRequest)(nil),  // 1: tenant.v1.PatchTenantRequest
	(*IsExistsResponse)(nil),    // 2: tenant.v1.IsExistsResponse
	(*PatchTenantResponse)(nil), // 3: tenant.v1.PatchTenantResponse
}
var file_public_tenant_v1_service_proto_depIdxs = []int32{
	0, // 0: tenant.v1.TenantPublicService.IsExists:input_type -> tenant.v1.IsExistsRequest
	1, // 1: tenant.v1.TenantPublicService.PatchTenant:input_type -> tenant.v1.PatchTenantRequest
	2, // 2: tenant.v1.TenantPublicService.IsExists:output_type -> tenant.v1.IsExistsResponse
	3, // 3: tenant.v1.TenantPublicService.PatchTenant:output_type -> tenant.v1.PatchTenantResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_tenant_v1_service_proto_init() }
func file_public_tenant_v1_service_proto_init() {
	if File_public_tenant_v1_service_proto != nil {
		return
	}
	file_public_tenant_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_tenant_v1_service_proto_rawDesc), len(file_public_tenant_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_tenant_v1_service_proto_goTypes,
		DependencyIndexes: file_public_tenant_v1_service_proto_depIdxs,
	}.Build()
	File_public_tenant_v1_service_proto = out.File
	file_public_tenant_v1_service_proto_goTypes = nil
	file_public_tenant_v1_service_proto_depIdxs = nil
}
