// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/tenant/v1/service.proto

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantPublicService_IsExists_FullMethodName    = "/tenant.v1.TenantPublicService/IsExists"
	TenantPublicService_PatchTenant_FullMethodName = "/tenant.v1.TenantPublicService/PatchTenant"
)

// TenantPublicServiceClient is the client API for TenantPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantPublicServiceClient interface {
	// Проверка на существование
	IsExists(ctx context.Context, in *IsExistsRequest, opts ...grpc.CallOption) (*IsExistsResponse, error)
	// Обновление тенанта
	PatchTenant(ctx context.Context, in *PatchTenantRequest, opts ...grpc.CallOption) (*PatchTenantResponse, error)
}

type tenantPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantPublicServiceClient(cc grpc.ClientConnInterface) TenantPublicServiceClient {
	return &tenantPublicServiceClient{cc}
}

func (c *tenantPublicServiceClient) IsExists(ctx context.Context, in *IsExistsRequest, opts ...grpc.CallOption) (*IsExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsExistsResponse)
	err := c.cc.Invoke(ctx, TenantPublicService_IsExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPublicServiceClient) PatchTenant(ctx context.Context, in *PatchTenantRequest, opts ...grpc.CallOption) (*PatchTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchTenantResponse)
	err := c.cc.Invoke(ctx, TenantPublicService_PatchTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantPublicServiceServer is the server API for TenantPublicService service.
// All implementations must embed UnimplementedTenantPublicServiceServer
// for forward compatibility.
type TenantPublicServiceServer interface {
	// Проверка на существование
	IsExists(context.Context, *IsExistsRequest) (*IsExistsResponse, error)
	// Обновление тенанта
	PatchTenant(context.Context, *PatchTenantRequest) (*PatchTenantResponse, error)
	mustEmbedUnimplementedTenantPublicServiceServer()
}

// UnimplementedTenantPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantPublicServiceServer struct{}

func (UnimplementedTenantPublicServiceServer) IsExists(context.Context, *IsExistsRequest) (*IsExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsExists not implemented")
}
func (UnimplementedTenantPublicServiceServer) PatchTenant(context.Context, *PatchTenantRequest) (*PatchTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchTenant not implemented")
}
func (UnimplementedTenantPublicServiceServer) mustEmbedUnimplementedTenantPublicServiceServer() {}
func (UnimplementedTenantPublicServiceServer) testEmbeddedByValue()                             {}

// UnsafeTenantPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantPublicServiceServer will
// result in compilation errors.
type UnsafeTenantPublicServiceServer interface {
	mustEmbedUnimplementedTenantPublicServiceServer()
}

func RegisterTenantPublicServiceServer(s grpc.ServiceRegistrar, srv TenantPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantPublicService_ServiceDesc, srv)
}

func _TenantPublicService_IsExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPublicServiceServer).IsExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPublicService_IsExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPublicServiceServer).IsExists(ctx, req.(*IsExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPublicService_PatchTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPublicServiceServer).PatchTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPublicService_PatchTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPublicServiceServer).PatchTenant(ctx, req.(*PatchTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantPublicService_ServiceDesc is the grpc.ServiceDesc for TenantPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.v1.TenantPublicService",
	HandlerType: (*TenantPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsExists",
			Handler:    _TenantPublicService_IsExists_Handler,
		},
		{
			MethodName: "PatchTenant",
			Handler:    _TenantPublicService_PatchTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/tenant/v1/service.proto",
}
