// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/rooms/v1/service.proto

package roomsv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_rooms_v1_service_proto protoreflect.FileDescriptor

const file_public_rooms_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dpublic/rooms/v1/service.proto\x12\brooms.v1\x1a\x19public/rooms/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd7\x01\n" +
	"\x12RoomsPublicService\x12V\n" +
	"\aGetRoom\x12\x18.rooms.v1.GetRoomRequest\x1a\x19.rooms.v1.GetRoomResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/rooms/{id}\x12i\n" +
	"\n" +
	"FinishRoom\x12\x1b.rooms.v1.FinishRoomRequest\x1a\x1c.rooms.v1.FinishRoomResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/rooms/{id}/finishB\xa2\x01\n" +
	"\fcom.rooms.v1B\fServiceProtoP\x01ZCgithub.com/neurochar/workflows/pkg/proto_pb/public/rooms/v1;roomsv1\xa2\x02\x03RXX\xaa\x02\bRooms.V1\xca\x02\bRooms\\V1\xe2\x02\x14Rooms\\V1\\GPBMetadata\xea\x02\tRooms::V1b\x06proto3"

var file_public_rooms_v1_service_proto_goTypes = []any{
	(*GetRoomRequest)(nil),     // 0: rooms.v1.GetRoomRequest
	(*FinishRoomRequest)(nil),  // 1: rooms.v1.FinishRoomRequest
	(*GetRoomResponse)(nil),    // 2: rooms.v1.GetRoomResponse
	(*FinishRoomResponse)(nil), // 3: rooms.v1.FinishRoomResponse
}
var file_public_rooms_v1_service_proto_depIdxs = []int32{
	0, // 0: rooms.v1.RoomsPublicService.GetRoom:input_type -> rooms.v1.GetRoomRequest
	1, // 1: rooms.v1.RoomsPublicService.FinishRoom:input_type -> rooms.v1.FinishRoomRequest
	2, // 2: rooms.v1.RoomsPublicService.GetRoom:output_type -> rooms.v1.GetRoomResponse
	3, // 3: rooms.v1.RoomsPublicService.FinishRoom:output_type -> rooms.v1.FinishRoomResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_rooms_v1_service_proto_init() }
func file_public_rooms_v1_service_proto_init() {
	if File_public_rooms_v1_service_proto != nil {
		return
	}
	file_public_rooms_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_rooms_v1_service_proto_rawDesc), len(file_public_rooms_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_rooms_v1_service_proto_goTypes,
		DependencyIndexes: file_public_rooms_v1_service_proto_depIdxs,
	}.Build()
	File_public_rooms_v1_service_proto = out.File
	file_public_rooms_v1_service_proto_goTypes = nil
	file_public_rooms_v1_service_proto_depIdxs = nil
}
