// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/rooms/v1/service.proto

package roomsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomsPublicService_GetRoom_FullMethodName    = "/rooms.v1.RoomsPublicService/GetRoom"
	RoomsPublicService_FinishRoom_FullMethodName = "/rooms.v1.RoomsPublicService/FinishRoom"
)

// RoomsPublicServiceClient is the client API for RoomsPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomsPublicServiceClient interface {
	// Получить комнату
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
	// Завершить комнату
	FinishRoom(ctx context.Context, in *FinishRoomRequest, opts ...grpc.CallOption) (*FinishRoomResponse, error)
}

type roomsPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomsPublicServiceClient(cc grpc.ClientConnInterface) RoomsPublicServiceClient {
	return &roomsPublicServiceClient{cc}
}

func (c *roomsPublicServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomResponse)
	err := c.cc.Invoke(ctx, RoomsPublicService_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomsPublicServiceClient) FinishRoom(ctx context.Context, in *FinishRoomRequest, opts ...grpc.CallOption) (*FinishRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRoomResponse)
	err := c.cc.Invoke(ctx, RoomsPublicService_FinishRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomsPublicServiceServer is the server API for RoomsPublicService service.
// All implementations must embed UnimplementedRoomsPublicServiceServer
// for forward compatibility.
type RoomsPublicServiceServer interface {
	// Получить комнату
	GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error)
	// Завершить комнату
	FinishRoom(context.Context, *FinishRoomRequest) (*FinishRoomResponse, error)
	mustEmbedUnimplementedRoomsPublicServiceServer()
}

// UnimplementedRoomsPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomsPublicServiceServer struct{}

func (UnimplementedRoomsPublicServiceServer) GetRoom(context.Context, *GetRoomRequest) (*GetRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedRoomsPublicServiceServer) FinishRoom(context.Context, *FinishRoomRequest) (*FinishRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishRoom not implemented")
}
func (UnimplementedRoomsPublicServiceServer) mustEmbedUnimplementedRoomsPublicServiceServer() {}
func (UnimplementedRoomsPublicServiceServer) testEmbeddedByValue()                            {}

// UnsafeRoomsPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomsPublicServiceServer will
// result in compilation errors.
type UnsafeRoomsPublicServiceServer interface {
	mustEmbedUnimplementedRoomsPublicServiceServer()
}

func RegisterRoomsPublicServiceServer(s grpc.ServiceRegistrar, srv RoomsPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomsPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomsPublicService_ServiceDesc, srv)
}

func _RoomsPublicService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomsPublicServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomsPublicService_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomsPublicServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomsPublicService_FinishRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomsPublicServiceServer).FinishRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomsPublicService_FinishRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomsPublicServiceServer).FinishRoom(ctx, req.(*FinishRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomsPublicService_ServiceDesc is the grpc.ServiceDesc for RoomsPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomsPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rooms.v1.RoomsPublicService",
	HandlerType: (*RoomsPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoom",
			Handler:    _RoomsPublicService_GetRoom_Handler,
		},
		{
			MethodName: "FinishRoom",
			Handler:    _RoomsPublicService_FinishRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/rooms/v1/service.proto",
}
