// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workers/word2pdf/word2pdf.proto

package word2pdfv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMsg_Start
	//	*ClientMsg_Chunk
	//	*ClientMsg_End
	//	*ClientMsg_Ping
	Payload       isClientMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMsg) GetPayload() isClientMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMsg) GetStart() *Start {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientMsg) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *ClientMsg) GetEnd() *End {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *ClientMsg) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMsg_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMsg_Payload interface {
	isClientMsg_Payload()
}

type ClientMsg_Start struct {
	Start *Start `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientMsg_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ClientMsg_End struct {
	End *End `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

type ClientMsg_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ClientMsg_Start) isClientMsg_Payload() {}

func (*ClientMsg_Chunk) isClientMsg_Payload() {}

func (*ClientMsg_End) isClientMsg_Payload() {}

func (*ClientMsg_Ping) isClientMsg_Payload() {}

type ServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMsg_Ready
	//	*ServerMsg_Pong
	//	*ServerMsg_Progress
	//	*ServerMsg_Result
	//	*ServerMsg_Error
	Payload       isServerMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMsg) GetPayload() isServerMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMsg) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ServerMsg) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMsg) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ServerMsg) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerMsg) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMsg_Payload interface {
	isServerMsg_Payload()
}

type ServerMsg_Ready struct {
	Ready *Ready `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ServerMsg_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type ServerMsg_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ServerMsg_Result struct {
	Result *Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type ServerMsg_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ServerMsg_Ready) isServerMsg_Payload() {}

func (*ServerMsg_Pong) isServerMsg_Payload() {}

func (*ServerMsg_Progress) isServerMsg_Payload() {}

func (*ServerMsg_Result) isServerMsg_Payload() {}

func (*ServerMsg_Error) isServerMsg_Payload() {}

type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{2}
}

func (x *Start) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Start) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Start) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type End struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *End) Reset() {
	*x = End{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{4}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ping) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{6}
}

func (x *Ready) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{7}
}

func (x *Pong) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pong) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Done          int32                  `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{8}
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetDone() int32 {
	if x != nil {
		return x.Done
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Result) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Result) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_workers_word2pdf_word2pdf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_workers_word2pdf_word2pdf_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workers_word2pdf_word2pdf_proto protoreflect.FileDescriptor

const file_workers_word2pdf_word2pdf_proto_rawDesc = "" +
	"\n" +
	"\x1fworkers/word2pdf/word2pdf.proto\x12\vword2pdf.v1\"\xc1\x01\n" +
	"\tClientMsg\x12*\n" +
	"\x05start\x18\x01 \x01(\v2\x12.word2pdf.v1.StartH\x00R\x05start\x12.\n" +
	"\x05chunk\x18\x02 \x01(\v2\x16.word2pdf.v1.FileChunkH\x00R\x05chunk\x12$\n" +
	"\x03end\x18\x03 \x01(\v2\x10.word2pdf.v1.EndH\x00R\x03end\x12'\n" +
	"\x04ping\x18\x04 \x01(\v2\x11.word2pdf.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xfb\x01\n" +
	"\tServerMsg\x12*\n" +
	"\x05ready\x18\x01 \x01(\v2\x12.word2pdf.v1.ReadyH\x00R\x05ready\x12'\n" +
	"\x04pong\x18\x02 \x01(\v2\x11.word2pdf.v1.PongH\x00R\x04pong\x123\n" +
	"\bprogress\x18\x03 \x01(\v2\x15.word2pdf.v1.ProgressH\x00R\bprogress\x12-\n" +
	"\x06result\x18\x04 \x01(\v2\x13.word2pdf.v1.ResultH\x00R\x06result\x12*\n" +
	"\x05error\x18\x05 \x01(\v2\x12.word2pdf.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"e\n" +
	"\x05Start\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x05\n" +
	"\x03End\"+\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"&\n" +
	"\x05Ready\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"+\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"4\n" +
	"\bProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x12\n" +
	"\x04done\x18\x02 \x01(\x05R\x04done\"W\n" +
	"\x06Result\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\x0fWord2PdfService\x12=\n" +
	"\aConvert\x12\x16.word2pdf.v1.ClientMsg\x1a\x16.word2pdf.v1.ServerMsg(\x010\x01B\xb6\x01\n" +
	"\x0fcom.word2pdf.v1B\rWord2pdfProtoP\x01ZGgithub.com/neurochar/workflows/pkg/proto_pb/workers/word2pdf;word2pdfv1\xa2\x02\x03WXX\xaa\x02\vWord2pdf.V1\xca\x02\vWord2pdf\\V1\xe2\x02\x17Word2pdf\\V1\\GPBMetadata\xea\x02\fWord2pdf::V1b\x06proto3"

var (
	file_workers_word2pdf_word2pdf_proto_rawDescOnce sync.Once
	file_workers_word2pdf_word2pdf_proto_rawDescData []byte
)

func file_workers_word2pdf_word2pdf_proto_rawDescGZIP() []byte {
	file_workers_word2pdf_word2pdf_proto_rawDescOnce.Do(func() {
		file_workers_word2pdf_word2pdf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_word2pdf_word2pdf_proto_rawDesc), len(file_workers_word2pdf_word2pdf_proto_rawDesc)))
	})
	return file_workers_word2pdf_word2pdf_proto_rawDescData
}

var file_workers_word2pdf_word2pdf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_workers_word2pdf_word2pdf_proto_goTypes = []any{
	(*ClientMsg)(nil), // 0: word2pdf.v1.ClientMsg
	(*ServerMsg)(nil), // 1: word2pdf.v1.ServerMsg
	(*Start)(nil),     // 2: word2pdf.v1.Start
	(*FileChunk)(nil), // 3: word2pdf.v1.FileChunk
	(*End)(nil),       // 4: word2pdf.v1.End
	(*Ping)(nil),      // 5: word2pdf.v1.Ping
	(*Ready)(nil),     // 6: word2pdf.v1.Ready
	(*Pong)(nil),      // 7: word2pdf.v1.Pong
	(*Progress)(nil),  // 8: word2pdf.v1.Progress
	(*Result)(nil),    // 9: word2pdf.v1.Result
	(*Error)(nil),     // 10: word2pdf.v1.Error
}
var file_workers_word2pdf_word2pdf_proto_depIdxs = []int32{
	2,  // 0: word2pdf.v1.ClientMsg.start:type_name -> word2pdf.v1.Start
	3,  // 1: word2pdf.v1.ClientMsg.chunk:type_name -> word2pdf.v1.FileChunk
	4,  // 2: word2pdf.v1.ClientMsg.end:type_name -> word2pdf.v1.End
	5,  // 3: word2pdf.v1.ClientMsg.ping:type_name -> word2pdf.v1.Ping
	6,  // 4: word2pdf.v1.ServerMsg.ready:type_name -> word2pdf.v1.Ready
	7,  // 5: word2pdf.v1.ServerMsg.pong:type_name -> word2pdf.v1.Pong
	8,  // 6: word2pdf.v1.ServerMsg.progress:type_name -> word2pdf.v1.Progress
	9,  // 7: word2pdf.v1.ServerMsg.result:type_name -> word2pdf.v1.Result
	10, // 8: word2pdf.v1.ServerMsg.error:type_name -> word2pdf.v1.Error
	0,  // 9: word2pdf.v1.Word2PdfService.Convert:input_type -> word2pdf.v1.ClientMsg
	1,  // 10: word2pdf.v1.Word2PdfService.Convert:output_type -> word2pdf.v1.ServerMsg
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_workers_word2pdf_word2pdf_proto_init() }
func file_workers_word2pdf_word2pdf_proto_init() {
	if File_workers_word2pdf_word2pdf_proto != nil {
		return
	}
	file_workers_word2pdf_word2pdf_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMsg_Start)(nil),
		(*ClientMsg_Chunk)(nil),
		(*ClientMsg_End)(nil),
		(*ClientMsg_Ping)(nil),
	}
	file_workers_word2pdf_word2pdf_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMsg_Ready)(nil),
		(*ServerMsg_Pong)(nil),
		(*ServerMsg_Progress)(nil),
		(*ServerMsg_Result)(nil),
		(*ServerMsg_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_word2pdf_word2pdf_proto_rawDesc), len(file_workers_word2pdf_word2pdf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workers_word2pdf_word2pdf_proto_goTypes,
		DependencyIndexes: file_workers_word2pdf_word2pdf_proto_depIdxs,
		MessageInfos:      file_workers_word2pdf_word2pdf_proto_msgTypes,
	}.Build()
	File_workers_word2pdf_word2pdf_proto = out.File
	file_workers_word2pdf_word2pdf_proto_goTypes = nil
	file_workers_word2pdf_word2pdf_proto_depIdxs = nil
}
