apiVersion: v1
kind: ConfigMap
metadata:
    name: workflows-config
    namespace: neurochar

data:
    TZ: Europe/Moscow
    WORKFLOWS_APP_NAME: workflows
    WORKFLOWS_APP_VERSION: "1.0.0"
    WORKFLOWS_APP_BASE_IS_PROD: "true"
    WORKFLOWS_APP_BASE_USE_FX_LOGGER: "false"
    WORKFLOWS_APP_BASE_USE_LOGGER: "true"
    TEMPORAL_HOST: temporal-frontend.neurochar.svc.cluster.local:7233
    TEMPORAL_NAMESPACE: neurochar
    STORAGE_S3_ENDPOINT: "https://storage.yandexcloud.net"
    STORAGE_S3_REGION: "ru-central1"
    STORAGE_S3_URL: "https://storage.yandexcloud.net"
    STORAGE_S3_URL_IS_HOST: "true"
    STORAGE_S3_URL_HOST_PREFIX: "https://"
    STORAGE_S3_URL_HOST_POSTFIX: ".storage.yandexcloud.net"
    BACKEND_GRPC_PRIVATE_ENDPOINT: backend-app-service.neurochar.svc.cluster.local:50052
    WORKERS_OCR_SERVICE: worker-ocr-gpu-service.neurochar.svc.cluster.local:50051
    WORKERS_OCR_READINESS: http://worker-ocr-gpu-service.neurochar.svc.cluster.local:8000/ready
    WORKERS_OCR_FALLBACK_SERVICE: worker-ocr-cpu-service.neurochar.svc.cluster.local:50051
    WORKERS_WORD2PDF_SERVICE: worker-word2pdf-service.neurochar.svc.cluster.local:50051
    WORKERS_WORD2PDF_READINESS: http://worker-word2pdf-service.neurochar.svc.cluster.local:8000/ready
    WORKERS_PD_REMOVER_SERVICE: http://worker-pd-remover-service.neurochar.svc.cluster.local:8000
    WORKERS_PD_REMOVER_READINESS: http://worker-pd-remover-service.neurochar.svc.cluster.local:8000/health
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: workflows-app-deployment
    namespace: neurochar

spec:
    replicas: 1

    selector:
        matchLabels:
            app: workflows-app

    template:
        metadata:
            labels:
                app: workflows-app

        spec:
            containers:
                - name: workflows-app
                  image: __WORKFLOWS_APP_VERSION__
                  imagePullPolicy: Always

                  envFrom:
                      - configMapRef:
                            name: workflows-config
                      - secretRef:
                            name: workflows-app-secret

                  resources:
                      requests:
                          ephemeral-storage: "100Mi"
                      limits:
                          ephemeral-storage: "250Mi"
