// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/auth_tenant/v1/dto.proto

package auth_tenantv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	types "github.com/neurochar/workflows/pkg/proto_pb/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tokens struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RefreshJwt     string                 `protobuf:"bytes,1,opt,name=refresh_jwt,json=refreshJwt,proto3" json:"refresh_jwt,omitempty"`
	RefreshLifeSec int32                  `protobuf:"varint,2,opt,name=refresh_life_sec,json=refreshLifeSec,proto3" json:"refresh_life_sec,omitempty"`
	AccessJwt      string                 `protobuf:"bytes,3,opt,name=access_jwt,json=accessJwt,proto3" json:"access_jwt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{0}
}

func (x *Tokens) GetRefreshJwt() string {
	if x != nil {
		return x.RefreshJwt
	}
	return ""
}

func (x *Tokens) GetRefreshLifeSec() int32 {
	if x != nil {
		return x.RefreshLifeSec
	}
	return 0
}

func (x *Tokens) GetAccessJwt() string {
	if x != nil {
		return x.AccessJwt
	}
	return ""
}

type WhoIAmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoIAmRequest) Reset() {
	*x = WhoIAmRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoIAmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoIAmRequest) ProtoMessage() {}

func (x *WhoIAmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoIAmRequest.ProtoReflect.Descriptor instead.
func (*WhoIAmRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{1}
}

type WhoIAmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *types.AccountTenant   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Tenant        *types.Tenant          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoIAmResponse) Reset() {
	*x = WhoIAmResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoIAmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoIAmResponse) ProtoMessage() {}

func (x *WhoIAmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoIAmResponse.ProtoReflect.Descriptor instead.
func (*WhoIAmResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{2}
}

func (x *WhoIAmResponse) GetAccount() *types.AccountTenant {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *WhoIAmResponse) GetTenant() *types.Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type AccountVerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeId        string                 `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountVerifyEmailRequest) Reset() {
	*x = AccountVerifyEmailRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountVerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerifyEmailRequest) ProtoMessage() {}

func (x *AccountVerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*AccountVerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{3}
}

func (x *AccountVerifyEmailRequest) GetCodeId() string {
	if x != nil {
		return x.CodeId
	}
	return ""
}

func (x *AccountVerifyEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AccountVerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountVerifyEmailResponse) Reset() {
	*x = AccountVerifyEmailResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountVerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerifyEmailResponse) ProtoMessage() {}

func (x *AccountVerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*AccountVerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{4}
}

type CheckAccountCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountCodeRequest) Reset() {
	*x = CheckAccountCodeRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountCodeRequest) ProtoMessage() {}

func (x *CheckAccountCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountCodeRequest.ProtoReflect.Descriptor instead.
func (*CheckAccountCodeRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAccountCodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckAccountCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CheckAccountCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountCodeResponse) Reset() {
	*x = CheckAccountCodeResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountCodeResponse) ProtoMessage() {}

func (x *CheckAccountCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountCodeResponse.ProtoReflect.Descriptor instead.
func (*CheckAccountCodeResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{6}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantTextId  string                 `protobuf:"bytes,3,opt,name=tenant_text_id,json=tenantTextId,proto3" json:"tenant_text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTenantTextId() string {
	if x != nil {
		return x.TenantTextId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *types.AccountTenant   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Tenant        *types.Tenant          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Tokens        *Tokens                `protobuf:"bytes,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetAccount() *types.AccountTenant {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *LoginResponse) GetTenant() *types.Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *LoginResponse) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{9}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{10}
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *Tokens                `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshResponse) GetTokens() *Tokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RequestPasswordRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	TenantTextId  string                 `protobuf:"bytes,2,opt,name=tenant_text_id,json=tenantTextId,proto3" json:"tenant_text_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordRecoveryRequest) Reset() {
	*x = RequestPasswordRecoveryRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordRecoveryRequest) ProtoMessage() {}

func (x *RequestPasswordRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordRecoveryRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{13}
}

func (x *RequestPasswordRecoveryRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestPasswordRecoveryRequest) GetTenantTextId() string {
	if x != nil {
		return x.TenantTextId
	}
	return ""
}

type RequestPasswordRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeId        string                 `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordRecoveryResponse) Reset() {
	*x = RequestPasswordRecoveryResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordRecoveryResponse) ProtoMessage() {}

func (x *RequestPasswordRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordRecoveryResponse.ProtoReflect.Descriptor instead.
func (*RequestPasswordRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{14}
}

func (x *RequestPasswordRecoveryResponse) GetCodeId() string {
	if x != nil {
		return x.CodeId
	}
	return ""
}

type UpdatePasswordByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Password2     string                 `protobuf:"bytes,4,opt,name=password2,proto3" json:"password2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordByCodeRequest) Reset() {
	*x = UpdatePasswordByCodeRequest{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordByCodeRequest) ProtoMessage() {}

func (x *UpdatePasswordByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordByCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordByCodeRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePasswordByCodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePasswordByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePasswordByCodeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdatePasswordByCodeRequest) GetPassword2() string {
	if x != nil {
		return x.Password2
	}
	return ""
}

type UpdatePasswordByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordByCodeResponse) Reset() {
	*x = UpdatePasswordByCodeResponse{}
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordByCodeResponse) ProtoMessage() {}

func (x *UpdatePasswordByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_tenant_v1_dto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordByCodeResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordByCodeResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_tenant_v1_dto_proto_rawDescGZIP(), []int{16}
}

var File_public_auth_tenant_v1_dto_proto protoreflect.FileDescriptor

const file_public_auth_tenant_v1_dto_proto_rawDesc = "" +
	"\n" +
	"\x1fpublic/auth_tenant/v1/dto.proto\x12\x0eauth_tenant.v1\x1a\x18common/types/types.proto\x1a\x1fcommon/types/tenant_types.proto\x1a%common/types/users_tenant_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"r\n" +
	"\x06Tokens\x12\x1f\n" +
	"\vrefresh_jwt\x18\x01 \x01(\tR\n" +
	"refreshJwt\x12(\n" +
	"\x10refresh_life_sec\x18\x02 \x01(\x05R\x0erefreshLifeSec\x12\x1d\n" +
	"\n" +
	"access_jwt\x18\x03 \x01(\tR\taccessJwt\"\x0f\n" +
	"\rWhoIAmRequest\"m\n" +
	"\x0eWhoIAmResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.types.v1.AccountTenantR\aaccount\x12(\n" +
	"\x06tenant\x18\x02 \x01(\v2\x10.types.v1.TenantR\x06tenant\"Z\n" +
	"\x19AccountVerifyEmailRequest\x12!\n" +
	"\acode_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06codeId\x12\x1a\n" +
	"\x04code\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04code\"\x1c\n" +
	"\x1aAccountVerifyEmailResponse\"O\n" +
	"\x17CheckAccountCodeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\x04code\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04code\"\x1a\n" +
	"\x18CheckAccountCodeResponse\"z\n" +
	"\fLoginRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12,\n" +
	"\x0etenant_text_id\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\ftenantTextId\"\x9c\x01\n" +
	"\rLoginResponse\x121\n" +
	"\aaccount\x18\x01 \x01(\v2\x17.types.v1.AccountTenantR\aaccount\x12(\n" +
	"\x06tenant\x18\x02 \x01(\v2\x10.types.v1.TenantR\x06tenant\x12.\n" +
	"\x06tokens\x18\x03 \x01(\v2\x16.auth_tenant.v1.TokensR\x06tokens\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"=\n" +
	"\x0eRefreshRequest\x12+\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\frefreshToken\"A\n" +
	"\x0fRefreshResponse\x12.\n" +
	"\x06tokens\x18\x01 \x01(\v2\x16.auth_tenant.v1.TokensR\x06tokens\"p\n" +
	"\x1eRequestPasswordRecoveryRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12,\n" +
	"\x0etenant_text_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\ftenantTextId\":\n" +
	"\x1fRequestPasswordRecoveryResponse\x12\x17\n" +
	"\acode_id\x18\x01 \x01(\tR\x06codeId\"\x9d\x01\n" +
	"\x1bUpdatePasswordByCodeRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\x04code\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04code\x12\"\n" +
	"\bpassword\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bpassword\x12$\n" +
	"\tpassword2\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tpassword2\"\x1e\n" +
	"\x1cUpdatePasswordByCodeResponseB\xc4\x01\n" +
	"\x12com.auth_tenant.v1B\bDtoProtoP\x01ZOgithub.com/neurochar/workflows/pkg/proto_pb/public/auth_tenant/v1;auth_tenantv1\xa2\x02\x03AXX\xaa\x02\rAuthTenant.V1\xca\x02\rAuthTenant\\V1\xe2\x02\x19AuthTenant\\V1\\GPBMetadata\xea\x02\x0eAuthTenant::V1b\x06proto3"

var (
	file_public_auth_tenant_v1_dto_proto_rawDescOnce sync.Once
	file_public_auth_tenant_v1_dto_proto_rawDescData []byte
)

func file_public_auth_tenant_v1_dto_proto_rawDescGZIP() []byte {
	file_public_auth_tenant_v1_dto_proto_rawDescOnce.Do(func() {
		file_public_auth_tenant_v1_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_auth_tenant_v1_dto_proto_rawDesc), len(file_public_auth_tenant_v1_dto_proto_rawDesc)))
	})
	return file_public_auth_tenant_v1_dto_proto_rawDescData
}

var file_public_auth_tenant_v1_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_public_auth_tenant_v1_dto_proto_goTypes = []any{
	(*Tokens)(nil),                          // 0: auth_tenant.v1.Tokens
	(*WhoIAmRequest)(nil),                   // 1: auth_tenant.v1.WhoIAmRequest
	(*WhoIAmResponse)(nil),                  // 2: auth_tenant.v1.WhoIAmResponse
	(*AccountVerifyEmailRequest)(nil),       // 3: auth_tenant.v1.AccountVerifyEmailRequest
	(*AccountVerifyEmailResponse)(nil),      // 4: auth_tenant.v1.AccountVerifyEmailResponse
	(*CheckAccountCodeRequest)(nil),         // 5: auth_tenant.v1.CheckAccountCodeRequest
	(*CheckAccountCodeResponse)(nil),        // 6: auth_tenant.v1.CheckAccountCodeResponse
	(*LoginRequest)(nil),                    // 7: auth_tenant.v1.LoginRequest
	(*LoginResponse)(nil),                   // 8: auth_tenant.v1.LoginResponse
	(*LogoutRequest)(nil),                   // 9: auth_tenant.v1.LogoutRequest
	(*LogoutResponse)(nil),                  // 10: auth_tenant.v1.LogoutResponse
	(*RefreshRequest)(nil),                  // 11: auth_tenant.v1.RefreshRequest
	(*RefreshResponse)(nil),                 // 12: auth_tenant.v1.RefreshResponse
	(*RequestPasswordRecoveryRequest)(nil),  // 13: auth_tenant.v1.RequestPasswordRecoveryRequest
	(*RequestPasswordRecoveryResponse)(nil), // 14: auth_tenant.v1.RequestPasswordRecoveryResponse
	(*UpdatePasswordByCodeRequest)(nil),     // 15: auth_tenant.v1.UpdatePasswordByCodeRequest
	(*UpdatePasswordByCodeResponse)(nil),    // 16: auth_tenant.v1.UpdatePasswordByCodeResponse
	(*types.AccountTenant)(nil),             // 17: types.v1.AccountTenant
	(*types.Tenant)(nil),                    // 18: types.v1.Tenant
}
var file_public_auth_tenant_v1_dto_proto_depIdxs = []int32{
	17, // 0: auth_tenant.v1.WhoIAmResponse.account:type_name -> types.v1.AccountTenant
	18, // 1: auth_tenant.v1.WhoIAmResponse.tenant:type_name -> types.v1.Tenant
	17, // 2: auth_tenant.v1.LoginResponse.account:type_name -> types.v1.AccountTenant
	18, // 3: auth_tenant.v1.LoginResponse.tenant:type_name -> types.v1.Tenant
	0,  // 4: auth_tenant.v1.LoginResponse.tokens:type_name -> auth_tenant.v1.Tokens
	0,  // 5: auth_tenant.v1.RefreshResponse.tokens:type_name -> auth_tenant.v1.Tokens
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_public_auth_tenant_v1_dto_proto_init() }
func file_public_auth_tenant_v1_dto_proto_init() {
	if File_public_auth_tenant_v1_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_auth_tenant_v1_dto_proto_rawDesc), len(file_public_auth_tenant_v1_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_auth_tenant_v1_dto_proto_goTypes,
		DependencyIndexes: file_public_auth_tenant_v1_dto_proto_depIdxs,
		MessageInfos:      file_public_auth_tenant_v1_dto_proto_msgTypes,
	}.Build()
	File_public_auth_tenant_v1_dto_proto = out.File
	file_public_auth_tenant_v1_dto_proto_goTypes = nil
	file_public_auth_tenant_v1_dto_proto_depIdxs = nil
}
