// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public/auth_tenant/v1/service.proto

package auth_tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthTenantPublicService_WhoIAm_FullMethodName                  = "/auth_tenant.v1.AuthTenantPublicService/WhoIAm"
	AuthTenantPublicService_AccountVerifyEmail_FullMethodName      = "/auth_tenant.v1.AuthTenantPublicService/AccountVerifyEmail"
	AuthTenantPublicService_CheckAccountCode_FullMethodName        = "/auth_tenant.v1.AuthTenantPublicService/CheckAccountCode"
	AuthTenantPublicService_Login_FullMethodName                   = "/auth_tenant.v1.AuthTenantPublicService/Login"
	AuthTenantPublicService_Logout_FullMethodName                  = "/auth_tenant.v1.AuthTenantPublicService/Logout"
	AuthTenantPublicService_Refresh_FullMethodName                 = "/auth_tenant.v1.AuthTenantPublicService/Refresh"
	AuthTenantPublicService_RequestPasswordRecovery_FullMethodName = "/auth_tenant.v1.AuthTenantPublicService/RequestPasswordRecovery"
	AuthTenantPublicService_UpdatePasswordByCode_FullMethodName    = "/auth_tenant.v1.AuthTenantPublicService/UpdatePasswordByCode"
)

// AuthTenantPublicServiceClient is the client API for AuthTenantPublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthTenantPublicServiceClient interface {
	// WhoIAm
	WhoIAm(ctx context.Context, in *WhoIAmRequest, opts ...grpc.CallOption) (*WhoIAmResponse, error)
	// Верификация аккаунта по емаил
	AccountVerifyEmail(ctx context.Context, in *AccountVerifyEmailRequest, opts ...grpc.CallOption) (*AccountVerifyEmailResponse, error)
	// Проверить код аккаунта
	CheckAccountCode(ctx context.Context, in *CheckAccountCodeRequest, opts ...grpc.CallOption) (*CheckAccountCodeResponse, error)
	// Login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Logout
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Refresh
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Запрос на восстановление пароля
	RequestPasswordRecovery(ctx context.Context, in *RequestPasswordRecoveryRequest, opts ...grpc.CallOption) (*RequestPasswordRecoveryResponse, error)
	// Обновить пароль по коду
	UpdatePasswordByCode(ctx context.Context, in *UpdatePasswordByCodeRequest, opts ...grpc.CallOption) (*UpdatePasswordByCodeResponse, error)
}

type authTenantPublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthTenantPublicServiceClient(cc grpc.ClientConnInterface) AuthTenantPublicServiceClient {
	return &authTenantPublicServiceClient{cc}
}

func (c *authTenantPublicServiceClient) WhoIAm(ctx context.Context, in *WhoIAmRequest, opts ...grpc.CallOption) (*WhoIAmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoIAmResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_WhoIAm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) AccountVerifyEmail(ctx context.Context, in *AccountVerifyEmailRequest, opts ...grpc.CallOption) (*AccountVerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountVerifyEmailResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_AccountVerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) CheckAccountCode(ctx context.Context, in *CheckAccountCodeRequest, opts ...grpc.CallOption) (*CheckAccountCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccountCodeResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_CheckAccountCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) RequestPasswordRecovery(ctx context.Context, in *RequestPasswordRecoveryRequest, opts ...grpc.CallOption) (*RequestPasswordRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPasswordRecoveryResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_RequestPasswordRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authTenantPublicServiceClient) UpdatePasswordByCode(ctx context.Context, in *UpdatePasswordByCodeRequest, opts ...grpc.CallOption) (*UpdatePasswordByCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasswordByCodeResponse)
	err := c.cc.Invoke(ctx, AuthTenantPublicService_UpdatePasswordByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthTenantPublicServiceServer is the server API for AuthTenantPublicService service.
// All implementations must embed UnimplementedAuthTenantPublicServiceServer
// for forward compatibility.
type AuthTenantPublicServiceServer interface {
	// WhoIAm
	WhoIAm(context.Context, *WhoIAmRequest) (*WhoIAmResponse, error)
	// Верификация аккаунта по емаил
	AccountVerifyEmail(context.Context, *AccountVerifyEmailRequest) (*AccountVerifyEmailResponse, error)
	// Проверить код аккаунта
	CheckAccountCode(context.Context, *CheckAccountCodeRequest) (*CheckAccountCodeResponse, error)
	// Login
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Logout
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Refresh
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Запрос на восстановление пароля
	RequestPasswordRecovery(context.Context, *RequestPasswordRecoveryRequest) (*RequestPasswordRecoveryResponse, error)
	// Обновить пароль по коду
	UpdatePasswordByCode(context.Context, *UpdatePasswordByCodeRequest) (*UpdatePasswordByCodeResponse, error)
	mustEmbedUnimplementedAuthTenantPublicServiceServer()
}

// UnimplementedAuthTenantPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthTenantPublicServiceServer struct{}

func (UnimplementedAuthTenantPublicServiceServer) WhoIAm(context.Context, *WhoIAmRequest) (*WhoIAmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoIAm not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) AccountVerifyEmail(context.Context, *AccountVerifyEmailRequest) (*AccountVerifyEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountVerifyEmail not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) CheckAccountCode(context.Context, *CheckAccountCodeRequest) (*CheckAccountCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccountCode not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) RequestPasswordRecovery(context.Context, *RequestPasswordRecoveryRequest) (*RequestPasswordRecoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPasswordRecovery not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) UpdatePasswordByCode(context.Context, *UpdatePasswordByCodeRequest) (*UpdatePasswordByCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePasswordByCode not implemented")
}
func (UnimplementedAuthTenantPublicServiceServer) mustEmbedUnimplementedAuthTenantPublicServiceServer() {
}
func (UnimplementedAuthTenantPublicServiceServer) testEmbeddedByValue() {}

// UnsafeAuthTenantPublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthTenantPublicServiceServer will
// result in compilation errors.
type UnsafeAuthTenantPublicServiceServer interface {
	mustEmbedUnimplementedAuthTenantPublicServiceServer()
}

func RegisterAuthTenantPublicServiceServer(s grpc.ServiceRegistrar, srv AuthTenantPublicServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthTenantPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthTenantPublicService_ServiceDesc, srv)
}

func _AuthTenantPublicService_WhoIAm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoIAmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).WhoIAm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_WhoIAm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).WhoIAm(ctx, req.(*WhoIAmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_AccountVerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountVerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).AccountVerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_AccountVerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).AccountVerifyEmail(ctx, req.(*AccountVerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_CheckAccountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).CheckAccountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_CheckAccountCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).CheckAccountCode(ctx, req.(*CheckAccountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_RequestPasswordRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPasswordRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).RequestPasswordRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_RequestPasswordRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).RequestPasswordRecovery(ctx, req.(*RequestPasswordRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthTenantPublicService_UpdatePasswordByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthTenantPublicServiceServer).UpdatePasswordByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthTenantPublicService_UpdatePasswordByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthTenantPublicServiceServer).UpdatePasswordByCode(ctx, req.(*UpdatePasswordByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthTenantPublicService_ServiceDesc is the grpc.ServiceDesc for AuthTenantPublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthTenantPublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_tenant.v1.AuthTenantPublicService",
	HandlerType: (*AuthTenantPublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhoIAm",
			Handler:    _AuthTenantPublicService_WhoIAm_Handler,
		},
		{
			MethodName: "AccountVerifyEmail",
			Handler:    _AuthTenantPublicService_AccountVerifyEmail_Handler,
		},
		{
			MethodName: "CheckAccountCode",
			Handler:    _AuthTenantPublicService_CheckAccountCode_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthTenantPublicService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthTenantPublicService_Logout_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AuthTenantPublicService_Refresh_Handler,
		},
		{
			MethodName: "RequestPasswordRecovery",
			Handler:    _AuthTenantPublicService_RequestPasswordRecovery_Handler,
		},
		{
			MethodName: "UpdatePasswordByCode",
			Handler:    _AuthTenantPublicService_UpdatePasswordByCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/auth_tenant/v1/service.proto",
}
