// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/auth_tenant/v1/service.proto

package auth_tenantv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_auth_tenant_v1_service_proto protoreflect.FileDescriptor

const file_public_auth_tenant_v1_service_proto_rawDesc = "" +
	"\n" +
	"#public/auth_tenant/v1/service.proto\x12\x0eauth_tenant.v1\x1a\x1fpublic/auth_tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe2\b\n" +
	"\x17AuthTenantPublicService\x12|\n" +
	"\x06WhoIAm\x12\x1d.auth_tenant.v1.WhoIAmRequest\x1a\x1e.auth_tenant.v1.WhoIAmResponse\"3\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/tenant/auth/whoiam\x12\x94\x01\n" +
	"\x12AccountVerifyEmail\x12).auth_tenant.v1.AccountVerifyEmailRequest\x1a*.auth_tenant.v1.AccountVerifyEmailResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/tenant/auth/verify-email\x12\x8c\x01\n" +
	"\x10CheckAccountCode\x12'.auth_tenant.v1.CheckAccountCodeRequest\x1a(.auth_tenant.v1.CheckAccountCodeResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/tenant/auth/check-code\x12f\n" +
	"\x05Login\x12\x1c.auth_tenant.v1.LoginRequest\x1a\x1d.auth_tenant.v1.LoginResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/tenant/auth/login\x12\x7f\n" +
	"\x06Logout\x12\x1d.auth_tenant.v1.LogoutRequest\x1a\x1e.auth_tenant.v1.LogoutResponse\"6\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/tenant/auth/logout\x12n\n" +
	"\aRefresh\x12\x1e.auth_tenant.v1.RefreshRequest\x1a\x1f.auth_tenant.v1.RefreshResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/tenant/auth/refresh\x12\xa8\x01\n" +
	"\x17RequestPasswordRecovery\x12..auth_tenant.v1.RequestPasswordRecoveryRequest\x1a/.auth_tenant.v1.RequestPasswordRecoveryResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/tenant/auth/password-recovery\x12\x9e\x01\n" +
	"\x14UpdatePasswordByCode\x12+.auth_tenant.v1.UpdatePasswordByCodeRequest\x1a,.auth_tenant.v1.UpdatePasswordByCodeResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/tenant/auth/password-by-codeB\xc8\x01\n" +
	"\x12com.auth_tenant.v1B\fServiceProtoP\x01ZOgithub.com/neurochar/workflows/pkg/proto_pb/public/auth_tenant/v1;auth_tenantv1\xa2\x02\x03AXX\xaa\x02\rAuthTenant.V1\xca\x02\rAuthTenant\\V1\xe2\x02\x19AuthTenant\\V1\\GPBMetadata\xea\x02\x0eAuthTenant::V1b\x06proto3"

var file_public_auth_tenant_v1_service_proto_goTypes = []any{
	(*WhoIAmRequest)(nil),                   // 0: auth_tenant.v1.WhoIAmRequest
	(*AccountVerifyEmailRequest)(nil),       // 1: auth_tenant.v1.AccountVerifyEmailRequest
	(*CheckAccountCodeRequest)(nil),         // 2: auth_tenant.v1.CheckAccountCodeRequest
	(*LoginRequest)(nil),                    // 3: auth_tenant.v1.LoginRequest
	(*LogoutRequest)(nil),                   // 4: auth_tenant.v1.LogoutRequest
	(*RefreshRequest)(nil),                  // 5: auth_tenant.v1.RefreshRequest
	(*RequestPasswordRecoveryRequest)(nil),  // 6: auth_tenant.v1.RequestPasswordRecoveryRequest
	(*UpdatePasswordByCodeRequest)(nil),     // 7: auth_tenant.v1.UpdatePasswordByCodeRequest
	(*WhoIAmResponse)(nil),                  // 8: auth_tenant.v1.WhoIAmResponse
	(*AccountVerifyEmailResponse)(nil),      // 9: auth_tenant.v1.AccountVerifyEmailResponse
	(*CheckAccountCodeResponse)(nil),        // 10: auth_tenant.v1.CheckAccountCodeResponse
	(*LoginResponse)(nil),                   // 11: auth_tenant.v1.LoginResponse
	(*LogoutResponse)(nil),                  // 12: auth_tenant.v1.LogoutResponse
	(*RefreshResponse)(nil),                 // 13: auth_tenant.v1.RefreshResponse
	(*RequestPasswordRecoveryResponse)(nil), // 14: auth_tenant.v1.RequestPasswordRecoveryResponse
	(*UpdatePasswordByCodeResponse)(nil),    // 15: auth_tenant.v1.UpdatePasswordByCodeResponse
}
var file_public_auth_tenant_v1_service_proto_depIdxs = []int32{
	0,  // 0: auth_tenant.v1.AuthTenantPublicService.WhoIAm:input_type -> auth_tenant.v1.WhoIAmRequest
	1,  // 1: auth_tenant.v1.AuthTenantPublicService.AccountVerifyEmail:input_type -> auth_tenant.v1.AccountVerifyEmailRequest
	2,  // 2: auth_tenant.v1.AuthTenantPublicService.CheckAccountCode:input_type -> auth_tenant.v1.CheckAccountCodeRequest
	3,  // 3: auth_tenant.v1.AuthTenantPublicService.Login:input_type -> auth_tenant.v1.LoginRequest
	4,  // 4: auth_tenant.v1.AuthTenantPublicService.Logout:input_type -> auth_tenant.v1.LogoutRequest
	5,  // 5: auth_tenant.v1.AuthTenantPublicService.Refresh:input_type -> auth_tenant.v1.RefreshRequest
	6,  // 6: auth_tenant.v1.AuthTenantPublicService.RequestPasswordRecovery:input_type -> auth_tenant.v1.RequestPasswordRecoveryRequest
	7,  // 7: auth_tenant.v1.AuthTenantPublicService.UpdatePasswordByCode:input_type -> auth_tenant.v1.UpdatePasswordByCodeRequest
	8,  // 8: auth_tenant.v1.AuthTenantPublicService.WhoIAm:output_type -> auth_tenant.v1.WhoIAmResponse
	9,  // 9: auth_tenant.v1.AuthTenantPublicService.AccountVerifyEmail:output_type -> auth_tenant.v1.AccountVerifyEmailResponse
	10, // 10: auth_tenant.v1.AuthTenantPublicService.CheckAccountCode:output_type -> auth_tenant.v1.CheckAccountCodeResponse
	11, // 11: auth_tenant.v1.AuthTenantPublicService.Login:output_type -> auth_tenant.v1.LoginResponse
	12, // 12: auth_tenant.v1.AuthTenantPublicService.Logout:output_type -> auth_tenant.v1.LogoutResponse
	13, // 13: auth_tenant.v1.AuthTenantPublicService.Refresh:output_type -> auth_tenant.v1.RefreshResponse
	14, // 14: auth_tenant.v1.AuthTenantPublicService.RequestPasswordRecovery:output_type -> auth_tenant.v1.RequestPasswordRecoveryResponse
	15, // 15: auth_tenant.v1.AuthTenantPublicService.UpdatePasswordByCode:output_type -> auth_tenant.v1.UpdatePasswordByCodeResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_public_auth_tenant_v1_service_proto_init() }
func file_public_auth_tenant_v1_service_proto_init() {
	if File_public_auth_tenant_v1_service_proto != nil {
		return
	}
	file_public_auth_tenant_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_auth_tenant_v1_service_proto_rawDesc), len(file_public_auth_tenant_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_auth_tenant_v1_service_proto_goTypes,
		DependencyIndexes: file_public_auth_tenant_v1_service_proto_depIdxs,
	}.Build()
	File_public_auth_tenant_v1_service_proto = out.File
	file_public_auth_tenant_v1_service_proto_goTypes = nil
	file_public_auth_tenant_v1_service_proto_depIdxs = nil
}
