// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/testing/v1/service.proto

package testingv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_testing_v1_service_proto protoreflect.FileDescriptor

const file_public_testing_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpublic/testing/v1/service.proto\x12\n" +
	"testing.v1\x1a\x1bpublic/testing/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe0\x0f\n" +
	"\x14TestingPublicService\x12\xa6\x01\n" +
	"\x14GetPersonalityTraits\x12'.testing.v1.GetPersonalityTraitsRequest\x1a(.testing.v1.GetPersonalityTraitsResponse\";\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02 \x12\x1e/v1/testing/personality_traits\x12\x84\x01\n" +
	"\fListProfiles\x12\x1f.testing.v1.ListProfilesRequest\x1a .testing.v1.ListProfilesResponse\"1\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/testing/profiles\x12\x83\x01\n" +
	"\n" +
	"GetProfile\x12\x1d.testing.v1.GetProfileRequest\x1a\x1e.testing.v1.GetProfileResponse\"6\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/testing/profiles/{id}\x12\x8a\x01\n" +
	"\rCreateProfile\x12 .testing.v1.CreateProfileRequest\x1a!.testing.v1.CreateProfileResponse\"4\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/testing/profiles\x12\x8c\x01\n" +
	"\fPatchProfile\x12\x1f.testing.v1.PatchProfileRequest\x1a .testing.v1.PatchProfileResponse\"9\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/v1/testing/profiles/{id}\x12\x8c\x01\n" +
	"\rDeleteProfile\x12 .testing.v1.DeleteProfileRequest\x1a!.testing.v1.DeleteProfileResponse\"6\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b*\x19/v1/testing/profiles/{id}\x12\xe5\x01\n" +
	" GenerateProfileDescriptionByName\x123.testing.v1.GenerateProfileDescriptionByNameRequest\x1a4.testing.v1.GenerateProfileDescriptionByNameResponse\"V\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02;\"9/v1/testing/profiles/generate-profile-description-by-name\x12\xfa\x01\n" +
	"%GenerateProfileTraitsMapByDescription\x128.testing.v1.GenerateProfileTraitsMapByDescriptionRequest\x1a9.testing.v1.GenerateProfileTraitsMapByDescriptionResponse\"\\\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02A\"?/v1/testing/profiles/generate-profile-traits-map-by-description\x12x\n" +
	"\tListRooms\x12\x1c.testing.v1.ListRoomsRequest\x1a\x1d.testing.v1.ListRoomsResponse\".\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/testing/rooms\x12w\n" +
	"\aGetRoom\x12\x1a.testing.v1.GetRoomRequest\x1a\x1b.testing.v1.GetRoomResponse\"3\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/testing/rooms/{id}\x12~\n" +
	"\n" +
	"CreateRoom\x12\x1d.testing.v1.CreateRoomRequest\x1a\x1e.testing.v1.CreateRoomResponse\"1\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/testing/rooms\x12\x80\x01\n" +
	"\n" +
	"DeleteRoom\x12\x1d.testing.v1.DeleteRoomRequest\x1a\x1e.testing.v1.DeleteRoomResponse\"3\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18*\x16/v1/testing/rooms/{id}\x12\x8b\x01\n" +
	"\vProcessRoom\x12\x1e.testing.v1.ProcessRoomRequest\x1a\x1f.testing.v1.ProcessRoomResponse\";\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02 \"\x1e/v1/testing/rooms/{id}/processB\xb0\x01\n" +
	"\x0ecom.testing.v1B\fServiceProtoP\x01ZGgithub.com/neurochar/workflows/pkg/proto_pb/public/testing/v1;testingv1\xa2\x02\x03TXX\xaa\x02\n" +
	"Testing.V1\xca\x02\n" +
	"Testing\\V1\xe2\x02\x16Testing\\V1\\GPBMetadata\xea\x02\vTesting::V1b\x06proto3"

var file_public_testing_v1_service_proto_goTypes = []any{
	(*GetPersonalityTraitsRequest)(nil),                   // 0: testing.v1.GetPersonalityTraitsRequest
	(*ListProfilesRequest)(nil),                           // 1: testing.v1.ListProfilesRequest
	(*GetProfileRequest)(nil),                             // 2: testing.v1.GetProfileRequest
	(*CreateProfileRequest)(nil),                          // 3: testing.v1.CreateProfileRequest
	(*PatchProfileRequest)(nil),                           // 4: testing.v1.PatchProfileRequest
	(*DeleteProfileRequest)(nil),                          // 5: testing.v1.DeleteProfileRequest
	(*GenerateProfileDescriptionByNameRequest)(nil),       // 6: testing.v1.GenerateProfileDescriptionByNameRequest
	(*GenerateProfileTraitsMapByDescriptionRequest)(nil),  // 7: testing.v1.GenerateProfileTraitsMapByDescriptionRequest
	(*ListRoomsRequest)(nil),                              // 8: testing.v1.ListRoomsRequest
	(*GetRoomRequest)(nil),                                // 9: testing.v1.GetRoomRequest
	(*CreateRoomRequest)(nil),                             // 10: testing.v1.CreateRoomRequest
	(*DeleteRoomRequest)(nil),                             // 11: testing.v1.DeleteRoomRequest
	(*ProcessRoomRequest)(nil),                            // 12: testing.v1.ProcessRoomRequest
	(*GetPersonalityTraitsResponse)(nil),                  // 13: testing.v1.GetPersonalityTraitsResponse
	(*ListProfilesResponse)(nil),                          // 14: testing.v1.ListProfilesResponse
	(*GetProfileResponse)(nil),                            // 15: testing.v1.GetProfileResponse
	(*CreateProfileResponse)(nil),                         // 16: testing.v1.CreateProfileResponse
	(*PatchProfileResponse)(nil),                          // 17: testing.v1.PatchProfileResponse
	(*DeleteProfileResponse)(nil),                         // 18: testing.v1.DeleteProfileResponse
	(*GenerateProfileDescriptionByNameResponse)(nil),      // 19: testing.v1.GenerateProfileDescriptionByNameResponse
	(*GenerateProfileTraitsMapByDescriptionResponse)(nil), // 20: testing.v1.GenerateProfileTraitsMapByDescriptionResponse
	(*ListRoomsResponse)(nil),                             // 21: testing.v1.ListRoomsResponse
	(*GetRoomResponse)(nil),                               // 22: testing.v1.GetRoomResponse
	(*CreateRoomResponse)(nil),                            // 23: testing.v1.CreateRoomResponse
	(*DeleteRoomResponse)(nil),                            // 24: testing.v1.DeleteRoomResponse
	(*ProcessRoomResponse)(nil),                           // 25: testing.v1.ProcessRoomResponse
}
var file_public_testing_v1_service_proto_depIdxs = []int32{
	0,  // 0: testing.v1.TestingPublicService.GetPersonalityTraits:input_type -> testing.v1.GetPersonalityTraitsRequest
	1,  // 1: testing.v1.TestingPublicService.ListProfiles:input_type -> testing.v1.ListProfilesRequest
	2,  // 2: testing.v1.TestingPublicService.GetProfile:input_type -> testing.v1.GetProfileRequest
	3,  // 3: testing.v1.TestingPublicService.CreateProfile:input_type -> testing.v1.CreateProfileRequest
	4,  // 4: testing.v1.TestingPublicService.PatchProfile:input_type -> testing.v1.PatchProfileRequest
	5,  // 5: testing.v1.TestingPublicService.DeleteProfile:input_type -> testing.v1.DeleteProfileRequest
	6,  // 6: testing.v1.TestingPublicService.GenerateProfileDescriptionByName:input_type -> testing.v1.GenerateProfileDescriptionByNameRequest
	7,  // 7: testing.v1.TestingPublicService.GenerateProfileTraitsMapByDescription:input_type -> testing.v1.GenerateProfileTraitsMapByDescriptionRequest
	8,  // 8: testing.v1.TestingPublicService.ListRooms:input_type -> testing.v1.ListRoomsRequest
	9,  // 9: testing.v1.TestingPublicService.GetRoom:input_type -> testing.v1.GetRoomRequest
	10, // 10: testing.v1.TestingPublicService.CreateRoom:input_type -> testing.v1.CreateRoomRequest
	11, // 11: testing.v1.TestingPublicService.DeleteRoom:input_type -> testing.v1.DeleteRoomRequest
	12, // 12: testing.v1.TestingPublicService.ProcessRoom:input_type -> testing.v1.ProcessRoomRequest
	13, // 13: testing.v1.TestingPublicService.GetPersonalityTraits:output_type -> testing.v1.GetPersonalityTraitsResponse
	14, // 14: testing.v1.TestingPublicService.ListProfiles:output_type -> testing.v1.ListProfilesResponse
	15, // 15: testing.v1.TestingPublicService.GetProfile:output_type -> testing.v1.GetProfileResponse
	16, // 16: testing.v1.TestingPublicService.CreateProfile:output_type -> testing.v1.CreateProfileResponse
	17, // 17: testing.v1.TestingPublicService.PatchProfile:output_type -> testing.v1.PatchProfileResponse
	18, // 18: testing.v1.TestingPublicService.DeleteProfile:output_type -> testing.v1.DeleteProfileResponse
	19, // 19: testing.v1.TestingPublicService.GenerateProfileDescriptionByName:output_type -> testing.v1.GenerateProfileDescriptionByNameResponse
	20, // 20: testing.v1.TestingPublicService.GenerateProfileTraitsMapByDescription:output_type -> testing.v1.GenerateProfileTraitsMapByDescriptionResponse
	21, // 21: testing.v1.TestingPublicService.ListRooms:output_type -> testing.v1.ListRoomsResponse
	22, // 22: testing.v1.TestingPublicService.GetRoom:output_type -> testing.v1.GetRoomResponse
	23, // 23: testing.v1.TestingPublicService.CreateRoom:output_type -> testing.v1.CreateRoomResponse
	24, // 24: testing.v1.TestingPublicService.DeleteRoom:output_type -> testing.v1.DeleteRoomResponse
	25, // 25: testing.v1.TestingPublicService.ProcessRoom:output_type -> testing.v1.ProcessRoomResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_public_testing_v1_service_proto_init() }
func file_public_testing_v1_service_proto_init() {
	if File_public_testing_v1_service_proto != nil {
		return
	}
	file_public_testing_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_testing_v1_service_proto_rawDesc), len(file_public_testing_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_testing_v1_service_proto_goTypes,
		DependencyIndexes: file_public_testing_v1_service_proto_depIdxs,
	}.Build()
	File_public_testing_v1_service_proto = out.File
	file_public_testing_v1_service_proto_goTypes = nil
	file_public_testing_v1_service_proto_depIdxs = nil
}
