// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/public.proto

package apiv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_public_proto protoreflect.FileDescriptor

const file_public_public_proto_rawDesc = "" +
	"\n" +
	"\x13public/public.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.protoB\xf2\x01\x92Ac\x12\x19\n" +
	"\x12Backend public API2\x031.0ZF\n" +
	"D\n" +
	"\n" +
	"BearerAuth\x126\b\x02\x12!JWT token. Format: Bearer <token>\x1a\rAuthorization \x02\n" +
	"\n" +
	"com.api.v1B\vPublicProtoP\x01Z8github.com/neurochar/workflows/pkg/proto_pb/public;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var file_public_public_proto_goTypes = []any{}
var file_public_public_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_public_proto_init() }
func file_public_public_proto_init() {
	if File_public_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_public_proto_rawDesc), len(file_public_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_public_proto_goTypes,
		DependencyIndexes: file_public_public_proto_depIdxs,
	}.Build()
	File_public_public_proto = out.File
	file_public_public_proto_goTypes = nil
	file_public_public_proto_depIdxs = nil
}
