// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/users_tenant/v1/service.proto

package users_tenantv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_public_users_tenant_v1_service_proto protoreflect.FileDescriptor

const file_public_users_tenant_v1_service_proto_rawDesc = "" +
	"\n" +
	"$public/users_tenant/v1/service.proto\x12\x0fusers_tenant.v1\x1a public/users_tenant/v1/dto.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xf8\b\n" +
	"\x18UsersTenantPublicService\x12\x8a\x01\n" +
	"\fListAccounts\x12$.users_tenant.v1.ListAccountsRequest\x1a%.users_tenant.v1.ListAccountsResponse\"-\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/tenant/users\x12\x89\x01\n" +
	"\n" +
	"GetAccount\x12\".users_tenant.v1.GetAccountRequest\x1a#.users_tenant.v1.GetAccountResponse\"2\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/tenant/users/{id}\x12\x90\x01\n" +
	"\rCreateAccount\x12%.users_tenant.v1.CreateAccountRequest\x1a&.users_tenant.v1.CreateAccountResponse\"0\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/tenant/users\x12\x92\x01\n" +
	"\fPatchAccount\x12$.users_tenant.v1.PatchAccountRequest\x1a%.users_tenant.v1.PatchAccountResponse\"5\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/v1/tenant/users/{id}\x12\xa1\x01\n" +
	"\x0fUpdateMyProfile\x12'.users_tenant.v1.UpdateMyProfileRequest\x1a(.users_tenant.v1.UpdateMyProfileResponse\";\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/v1/tenant/users/my-profile\x12\xa5\x01\n" +
	"\x10UpdateMyPassword\x12(.users_tenant.v1.UpdateMyPasswordRequest\x1a).users_tenant.v1.UpdateMyPasswordResponse\"<\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/v1/tenant/users/my-password\x12\xce\x01\n" +
	"\x16UploadProfilePhotoFile\x12..users_tenant.v1.UploadProfilePhotoFileRequest\x1a/.users_tenant.v1.UploadProfilePhotoFileResponse\"S\x92A'2\x13multipart/form-datab\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/tenant/users/profile-photoB\xcf\x01\n" +
	"\x13com.users_tenant.v1B\fServiceProtoP\x01ZQgithub.com/neurochar/workflows/pkg/proto_pb/public/users_tenant/v1;users_tenantv1\xa2\x02\x03UXX\xaa\x02\x0eUsersTenant.V1\xca\x02\x0eUsersTenant\\V1\xe2\x02\x1aUsersTenant\\V1\\GPBMetadata\xea\x02\x0fUsersTenant::V1b\x06proto3"

var file_public_users_tenant_v1_service_proto_goTypes = []any{
	(*ListAccountsRequest)(nil),            // 0: users_tenant.v1.ListAccountsRequest
	(*GetAccountRequest)(nil),              // 1: users_tenant.v1.GetAccountRequest
	(*CreateAccountRequest)(nil),           // 2: users_tenant.v1.CreateAccountRequest
	(*PatchAccountRequest)(nil),            // 3: users_tenant.v1.PatchAccountRequest
	(*UpdateMyProfileRequest)(nil),         // 4: users_tenant.v1.UpdateMyProfileRequest
	(*UpdateMyPasswordRequest)(nil),        // 5: users_tenant.v1.UpdateMyPasswordRequest
	(*UploadProfilePhotoFileRequest)(nil),  // 6: users_tenant.v1.UploadProfilePhotoFileRequest
	(*ListAccountsResponse)(nil),           // 7: users_tenant.v1.ListAccountsResponse
	(*GetAccountResponse)(nil),             // 8: users_tenant.v1.GetAccountResponse
	(*CreateAccountResponse)(nil),          // 9: users_tenant.v1.CreateAccountResponse
	(*PatchAccountResponse)(nil),           // 10: users_tenant.v1.PatchAccountResponse
	(*UpdateMyProfileResponse)(nil),        // 11: users_tenant.v1.UpdateMyProfileResponse
	(*UpdateMyPasswordResponse)(nil),       // 12: users_tenant.v1.UpdateMyPasswordResponse
	(*UploadProfilePhotoFileResponse)(nil), // 13: users_tenant.v1.UploadProfilePhotoFileResponse
}
var file_public_users_tenant_v1_service_proto_depIdxs = []int32{
	0,  // 0: users_tenant.v1.UsersTenantPublicService.ListAccounts:input_type -> users_tenant.v1.ListAccountsRequest
	1,  // 1: users_tenant.v1.UsersTenantPublicService.GetAccount:input_type -> users_tenant.v1.GetAccountRequest
	2,  // 2: users_tenant.v1.UsersTenantPublicService.CreateAccount:input_type -> users_tenant.v1.CreateAccountRequest
	3,  // 3: users_tenant.v1.UsersTenantPublicService.PatchAccount:input_type -> users_tenant.v1.PatchAccountRequest
	4,  // 4: users_tenant.v1.UsersTenantPublicService.UpdateMyProfile:input_type -> users_tenant.v1.UpdateMyProfileRequest
	5,  // 5: users_tenant.v1.UsersTenantPublicService.UpdateMyPassword:input_type -> users_tenant.v1.UpdateMyPasswordRequest
	6,  // 6: users_tenant.v1.UsersTenantPublicService.UploadProfilePhotoFile:input_type -> users_tenant.v1.UploadProfilePhotoFileRequest
	7,  // 7: users_tenant.v1.UsersTenantPublicService.ListAccounts:output_type -> users_tenant.v1.ListAccountsResponse
	8,  // 8: users_tenant.v1.UsersTenantPublicService.GetAccount:output_type -> users_tenant.v1.GetAccountResponse
	9,  // 9: users_tenant.v1.UsersTenantPublicService.CreateAccount:output_type -> users_tenant.v1.CreateAccountResponse
	10, // 10: users_tenant.v1.UsersTenantPublicService.PatchAccount:output_type -> users_tenant.v1.PatchAccountResponse
	11, // 11: users_tenant.v1.UsersTenantPublicService.UpdateMyProfile:output_type -> users_tenant.v1.UpdateMyProfileResponse
	12, // 12: users_tenant.v1.UsersTenantPublicService.UpdateMyPassword:output_type -> users_tenant.v1.UpdateMyPasswordResponse
	13, // 13: users_tenant.v1.UsersTenantPublicService.UploadProfilePhotoFile:output_type -> users_tenant.v1.UploadProfilePhotoFileResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_public_users_tenant_v1_service_proto_init() }
func file_public_users_tenant_v1_service_proto_init() {
	if File_public_users_tenant_v1_service_proto != nil {
		return
	}
	file_public_users_tenant_v1_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_users_tenant_v1_service_proto_rawDesc), len(file_public_users_tenant_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_users_tenant_v1_service_proto_goTypes,
		DependencyIndexes: file_public_users_tenant_v1_service_proto_depIdxs,
	}.Build()
	File_public_users_tenant_v1_service_proto = out.File
	file_public_users_tenant_v1_service_proto_goTypes = nil
	file_public_users_tenant_v1_service_proto_depIdxs = nil
}
